//! Packet `ping` (status/clientbound, id 0x01).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/status/clientbound/ping.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Status, Clientbound)`.
pub const PACKET_ID: i32 = 0x01;

/// Ping packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct Ping {
    /// Auto-generated field.
    pub time: i64,
}

impl Ping {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let __buf = reader.read_exact(8)?;
        let time = i64::from_be_bytes([__buf[0],__buf[1],__buf[2],__buf[3],__buf[4],__buf[5],__buf[6],__buf[7]]);
        Ok(Self { time })
    }
}

impl ClientboundPacket for Ping {
    fn state(&self) -> ConnectionState { ConnectionState::Status }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&self.time.to_be_bytes())?;
        Ok(())
    }
}
