//! Packet `server_info` (status/clientbound, id 0x00).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/status/clientbound/server_info.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Status, Clientbound)`.
pub const PACKET_ID: i32 = 0x00;

/// ServerInfo packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct ServerInfo {
    /// Auto-generated field.
    pub response: String,
}

impl ServerInfo {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let response = string::read(reader)?;
        Ok(Self { response })
    }
}

impl ClientboundPacket for ServerInfo {
    fn state(&self) -> ConnectionState {
        ConnectionState::Status
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        string::write(&self.response, writer)?;
        Ok(())
    }
}
