//! Packet `legacy_server_list_ping` (handshaking/serverbound, id 0xFE).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/handshaking/serverbound/legacy_server_list_ping.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0xFE;
