//! Packet `legacy_server_list_ping` (handshaking/serverbound, id 0xFE).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/handshaking/serverbound/legacy_server_list_ping.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Handshaking, Serverbound)`.
pub const PACKET_ID: i32 = 0xFE;

/// LegacyServerListPing packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct LegacyServerListPing {
    /// Auto-generated field.
    pub payload: Vec<u8>,
}

impl LegacyServerListPing {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let payload = reader.read_exact(reader.remaining())?.to_vec();
        Ok(Self { payload })
    }
}

impl ServerboundPacket for LegacyServerListPing {
    fn state(&self) -> ConnectionState { ConnectionState::Handshaking }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&self.payload)?;
        Ok(())
    }
}
