//! Packet `set_protocol` (handshaking/serverbound, id 0x00).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/handshaking/serverbound/set_protocol.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Handshaking, Serverbound)`.
pub const PACKET_ID: i32 = 0x00;

/// SetProtocol packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct SetProtocol {
    /// Auto-generated field.
    pub protocol_version: i32,
    /// Auto-generated field.
    pub server_host: String,
    /// Auto-generated field.
    pub server_port: u16,
    /// Auto-generated field.
    pub next_state: i32,
}

impl SetProtocol {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let protocol_version = varint::read(reader)?;
        let server_host = string::read(reader)?;
        let __buf = reader.read_exact(2)?;
        let server_port = u16::from_be_bytes([__buf[0],__buf[1]]);
        let next_state = varint::read(reader)?;
        Ok(Self { protocol_version, server_host, server_port, next_state })
    }
}

impl ServerboundPacket for SetProtocol {
    fn state(&self) -> ConnectionState { ConnectionState::Handshaking }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.protocol_version, writer)?;
        string::write(&self.server_host, writer)?;
        writer.write_all(&self.server_port.to_be_bytes())?;
        varint::write(self.next_state, writer)?;
        Ok(())
    }
}
