"""Entity subclass for `camel` (type id 10).

Auto-generated by ``tools/generate_entity_subclasses.py``.

Hand-edits BELOW the auto-generated block are preserved across
re-generation. Hand-edits inside the auto block are wiped.
"""

from __future__ import annotations

from minecraft_bot.entities.base import Entity


class Camel(Entity):
    """`Camel` entity (Passive mobs category)."""

    ENTITY_TYPE_ID = 10
    ENTITY_NAME = "camel"

    # >>> auto-generated metadata accessors — DO NOT EDIT BELOW
    @property
    def shared_flags(self):
        """Metadata index 0: ``shared_flags``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(0)

    @property
    def air_supply(self):
        """Metadata index 1: ``air_supply``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(1)

    @property
    def custom_name(self):
        """Metadata index 2: ``custom_name``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(2)

    @property
    def custom_name_visible(self):
        """Metadata index 3: ``custom_name_visible``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(3)

    @property
    def silent(self):
        """Metadata index 4: ``silent``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(4)

    @property
    def no_gravity(self):
        """Metadata index 5: ``no_gravity``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(5)

    @property
    def pose(self):
        """Metadata index 6: ``pose``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(6)

    @property
    def ticks_frozen(self):
        """Metadata index 7: ``ticks_frozen``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(7)

    @property
    def living_entity_flags(self):
        """Metadata index 8: ``living_entity_flags``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(8)

    @property
    def health(self):
        """Metadata index 9: ``health``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(9)

    @property
    def effect_color(self):
        """Metadata index 10: ``effect_color``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(10)

    @property
    def effect_ambience(self):
        """Metadata index 11: ``effect_ambience``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(11)

    @property
    def arrow_count(self):
        """Metadata index 12: ``arrow_count``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(12)

    @property
    def stinger_count(self):
        """Metadata index 13: ``stinger_count``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(13)

    @property
    def sleeping_pos(self):
        """Metadata index 14: ``sleeping_pos``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(14)

    @property
    def mob_flags(self):
        """Metadata index 15: ``mob_flags``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(15)

    @property
    def baby(self):
        """Metadata index 16: ``baby``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(16)

    @property
    def flags(self):
        """Metadata index 17: ``flags``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(17)

    @property
    def dash(self):
        """Metadata index 18: ``dash``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(18)

    @property
    def last_pose_change_tick(self):
        """Metadata index 19: ``last_pose_change_tick``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(19)

    # <<< auto-generated metadata accessors
