"""Entity subclass for `falling_block` (type id 36).

Auto-generated by ``tools/generate_entity_subclasses.py``.

Hand-edits BELOW the auto-generated block are preserved across
re-generation. Hand-edits inside the auto block are wiped.
"""

from __future__ import annotations

from minecraft_bot.entities.base import Entity


class FallingBlock(Entity):
    """`Falling Block` entity (UNKNOWN category)."""

    ENTITY_TYPE_ID = 36
    ENTITY_NAME = "falling_block"

    # >>> auto-generated metadata accessors — DO NOT EDIT BELOW
    @property
    def shared_flags(self):
        """Metadata index 0: ``shared_flags``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(0)

    @property
    def air_supply(self):
        """Metadata index 1: ``air_supply``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(1)

    @property
    def custom_name(self):
        """Metadata index 2: ``custom_name``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(2)

    @property
    def custom_name_visible(self):
        """Metadata index 3: ``custom_name_visible``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(3)

    @property
    def silent(self):
        """Metadata index 4: ``silent``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(4)

    @property
    def no_gravity(self):
        """Metadata index 5: ``no_gravity``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(5)

    @property
    def pose(self):
        """Metadata index 6: ``pose``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(6)

    @property
    def ticks_frozen(self):
        """Metadata index 7: ``ticks_frozen``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(7)

    @property
    def start_pos(self):
        """Metadata index 8: ``start_pos``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(8)

    # <<< auto-generated metadata accessors
