"""Entity subclass for `text_display` (type id 100).

Auto-generated by ``tools/generate_entity_subclasses.py``.

Hand-edits BELOW the auto-generated block are preserved across
re-generation. Hand-edits inside the auto block are wiped.
"""

from __future__ import annotations

from minecraft_bot.entities.base import Entity


class TextDisplay(Entity):
    """`Text Display` entity (Immobile category)."""

    ENTITY_TYPE_ID = 100
    ENTITY_NAME = "text_display"

    # >>> auto-generated metadata accessors — DO NOT EDIT BELOW
    @property
    def shared_flags(self):
        """Metadata index 0: ``shared_flags``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(0)

    @property
    def air_supply(self):
        """Metadata index 1: ``air_supply``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(1)

    @property
    def custom_name(self):
        """Metadata index 2: ``custom_name``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(2)

    @property
    def custom_name_visible(self):
        """Metadata index 3: ``custom_name_visible``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(3)

    @property
    def silent(self):
        """Metadata index 4: ``silent``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(4)

    @property
    def no_gravity(self):
        """Metadata index 5: ``no_gravity``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(5)

    @property
    def pose(self):
        """Metadata index 6: ``pose``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(6)

    @property
    def ticks_frozen(self):
        """Metadata index 7: ``ticks_frozen``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(7)

    @property
    def interpolation_start_delta_ticks(self):
        """Metadata index 8: ``interpolation_start_delta_ticks``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(8)

    @property
    def interpolation_duration(self):
        """Metadata index 9: ``interpolation_duration``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(9)

    @property
    def translation(self):
        """Metadata index 10: ``translation``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(10)

    @property
    def scale(self):
        """Metadata index 11: ``scale``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(11)

    @property
    def left_rotation(self):
        """Metadata index 12: ``left_rotation``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(12)

    @property
    def right_rotation(self):
        """Metadata index 13: ``right_rotation``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(13)

    @property
    def billboard_render_constraints(self):
        """Metadata index 14: ``billboard_render_constraints``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(14)

    @property
    def brightness_override(self):
        """Metadata index 15: ``brightness_override``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(15)

    @property
    def view_range(self):
        """Metadata index 16: ``view_range``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(16)

    @property
    def shadow_radius(self):
        """Metadata index 17: ``shadow_radius``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(17)

    @property
    def shadow_strength(self):
        """Metadata index 18: ``shadow_strength``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(18)

    @property
    def width(self):
        """Metadata index 19: ``width``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(19)

    @property
    def height(self):
        """Metadata index 20: ``height``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(20)

    @property
    def glow_color_override(self):
        """Metadata index 21: ``glow_color_override``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(21)

    @property
    def text(self):
        """Metadata index 22: ``text``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(22)

    @property
    def line_width(self):
        """Metadata index 23: ``line_width``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(23)

    @property
    def background_color(self):
        """Metadata index 24: ``background_color``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(24)

    @property
    def text_opacity(self):
        """Metadata index 25: ``text_opacity``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(25)

    @property
    def style_flags(self):
        """Metadata index 26: ``style_flags``.

        Returns the raw decoded value from the entity's data-watcher
        stream, or ``None`` if the index has not been populated by
        the server (entity hasn't sent a metadata update for it yet).
        """
        return self.metadata.get(26)

    # <<< auto-generated metadata accessors
