//! Packet `abilities` (play/serverbound, id 0x1C).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/abilities.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x1C;

/// Abilities packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct Abilities {
    /// Auto-generated field.
    pub flags: i8,
}

impl Abilities {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let __buf = reader.read_exact(1)?;
        let flags = __buf[0] as i8;
        Ok(Self { flags })
    }
}

impl ServerboundPacket for Abilities {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&[self.flags as u8])?;
        Ok(())
    }
}
