//! Packet `advancement_tab` (play/serverbound, id 0x25).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/advancement_tab.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x25;

/// AdvancementTab packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct AdvancementTab {
    /// Auto-generated field.
    pub action: i32,
    /// Auto-generated field.
    pub tab_id: Option<String>,
}

impl AdvancementTab {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let action = varint::read(reader)?;
        let mut tab_id: Option<String> = None;
        if action == 0 {
            tab_id = Some(string::read(reader)?);
        }
        Ok(Self { action, tab_id })
    }
}

impl ServerboundPacket for AdvancementTab {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.action, writer)?;
        Ok(())
    }
}
