//! Packet `arm_animation` (play/serverbound, id 0x2F).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/arm_animation.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x2F;

/// ArmAnimation packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct ArmAnimation {
    /// Auto-generated field.
    pub hand: i32,
}

impl ArmAnimation {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let hand = varint::read(reader)?;
        Ok(Self { hand })
    }
}

impl ServerboundPacket for ArmAnimation {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.hand, writer)?;
        Ok(())
    }
}
