//! Packet `block_dig` (play/serverbound, id 0x1D).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/block_dig.py.

use crate::codec::position;
use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x1D;

/// BlockDig packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct BlockDig {
    /// Auto-generated field.
    pub status: i32,
    /// Auto-generated field.
    pub location: (i32, i32, i32),
    /// Auto-generated field.
    pub face: i8,
    /// Auto-generated field.
    pub sequence: i32,
}

impl BlockDig {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let status = varint::read(reader)?;
        let location = position::read(reader)?;
        let __buf = reader.read_exact(1)?;
        let face = __buf[0] as i8;
        let sequence = varint::read(reader)?;
        Ok(Self {
            status,
            location,
            face,
            sequence,
        })
    }
}

impl ServerboundPacket for BlockDig {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.status, writer)?;
        position::write(&self.location, writer)?;
        writer.write_all(&[self.face as u8])?;
        varint::write(self.sequence, writer)?;
        Ok(())
    }
}
