//! Packet `block_dig` (play/serverbound, id 0x1D).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/block_dig.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::codec::position;
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x1D;

/// BlockDig packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct BlockDig {
    /// Auto-generated field.
    pub st: i32,
    /// Auto-generated field.
    pub loc: (i32, i32, i32),
    /// Auto-generated field.
    pub f: i8,
    /// Auto-generated field.
    pub seq: i32,
}

impl BlockDig {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let st = varint::read(reader)?;
        let loc = position::read(reader)?;
        let __buf = reader.read_exact(1)?;
        let f = __buf[0] as i8;
        let seq = varint::read(reader)?;
        Ok(Self { st, loc, f, seq })
    }
}

impl ServerboundPacket for BlockDig {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.st, writer)?;
        position::write(&self.loc, writer)?;
        writer.write_all(&[self.f as u8])?;
        varint::write(self.seq, writer)?;
        Ok(())
    }
}
