//! Packet `block_place` (play/serverbound, id 0x31).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/block_place.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::codec::position;
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x31;

/// BlockPlace packet body (auto-generated).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct BlockPlace {
    /// Auto-generated field.
    pub hand: i32,
    /// Auto-generated field.
    pub location: (i32, i32, i32),
    /// Auto-generated field.
    pub direction: i32,
    /// Auto-generated field.
    pub cursor_x: f32,
    /// Auto-generated field.
    pub cursor_y: f32,
    /// Auto-generated field.
    pub cursor_z: f32,
    /// Auto-generated field.
    pub inside_block: bool,
    /// Auto-generated field.
    pub sequence: i32,
}

impl BlockPlace {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let hand = varint::read(reader)?;
        let location = position::read(reader)?;
        let direction = varint::read(reader)?;
        let __buf = reader.read_exact(12)?;
        let cursor_x = f32::from_be_bytes([__buf[0],__buf[1],__buf[2],__buf[3]]);
        let cursor_y = f32::from_be_bytes([__buf[4],__buf[5],__buf[6],__buf[7]]);
        let cursor_z = f32::from_be_bytes([__buf[8],__buf[9],__buf[10],__buf[11]]);
        let inside_block = { let __b = reader.read_exact(1)?[0]; if __b > 1 { return Err(ProtocolError::DecodeError(format!("inside_block: {}", __b))); } __b != 0 };
        let sequence = varint::read(reader)?;
        Ok(Self { hand, location, direction, cursor_x, cursor_y, cursor_z, inside_block, sequence })
    }
}

impl ServerboundPacket for BlockPlace {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.hand, writer)?;
        position::write(&self.location, writer)?;
        varint::write(self.direction, writer)?;
        writer.write_all(&self.cursor_x.to_be_bytes())?;
        writer.write_all(&self.cursor_y.to_be_bytes())?;
        writer.write_all(&self.cursor_z.to_be_bytes())?;
        writer.write_all(&[if self.inside_block { 1 } else { 0 }])?;
        varint::write(self.sequence, writer)?;
        Ok(())
    }
}
