//! Packet `chat_message` (play/serverbound, id 0x05).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/chat_message.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x05;

/// ChatMessage packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct ChatMessage {
    /// Auto-generated field.
    pub message: String,
    /// Auto-generated field.
    pub timestamp: i64,
    /// Auto-generated field.
    pub salt: i64,
    /// Auto-generated field.
    pub signature: Option<Vec<u8>>,
    /// Auto-generated field.
    pub message_count: i32,
    /// Auto-generated field.
    pub acknowledged: [u8; 3],
}

impl ChatMessage {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let message = string::read(reader)?;
        let __buf = reader.read_exact(16)?;
        let timestamp = i64::from_be_bytes([
            __buf[0], __buf[1], __buf[2], __buf[3], __buf[4], __buf[5], __buf[6], __buf[7],
        ]);
        let salt = i64::from_be_bytes([
            __buf[8], __buf[9], __buf[10], __buf[11], __buf[12], __buf[13], __buf[14], __buf[15],
        ]);
        let present = reader.read_exact(1)?[0];
        let signature = match present {
            0 => None,
            1 => Some(reader.read_exact(256)?.to_vec()),
            other => {
                return Err(ProtocolError::DecodeError(format!(
                    "signature.present: {}",
                    other
                )))
            }
        };
        let message_count = varint::read(reader)?;
        let __buf = reader.read_exact(3)?;
        let mut acknowledged = [0u8; 3];
        acknowledged.copy_from_slice(__buf);
        Ok(Self {
            message,
            timestamp,
            salt,
            signature,
            message_count,
            acknowledged,
        })
    }
}

impl ServerboundPacket for ChatMessage {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        string::write(&self.message, writer)?;
        writer.write_all(&self.timestamp.to_be_bytes())?;
        writer.write_all(&self.salt.to_be_bytes())?;
        match &self.signature {
            None => writer.write_all(&[0])?,
            Some(v) => {
                writer.write_all(&[1])?;
            }
        }
        varint::write(self.message_count, writer)?;
        writer.write_all(&self.acknowledged)?;
        Ok(())
    }
}
