//! Packet `chat_command` (play/serverbound, id 0x04).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/chat_command.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x04;

/// ChatCommand packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct ChatCommand {
    /// Auto-generated field.
    pub command: String,
    /// Auto-generated field.
    pub payload: Vec<u8>,
}

impl ChatCommand {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let command = string::read(reader)?;
        let payload = reader.read_exact(reader.remaining())?.to_vec();
        Ok(Self { command, payload })
    }
}

impl ServerboundPacket for ChatCommand {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        string::write(&self.command, writer)?;
        writer.write_all(&self.payload)?;
        Ok(())
    }
}
