//! Packet `chat_session_update` (play/serverbound, id 0x06).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/chat_session_update.py.

use crate::codec::uuid_codec::{self as uuid_c, Uuid};
use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x06;

/// ChatSessionUpdate packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct ChatSessionUpdate {
    /// Auto-generated field.
    pub session_uuid: Uuid,
    /// Auto-generated field.
    pub expire_time: i64,
    /// Auto-generated field.
    pub pk_len: i32,
    /// Auto-generated field.
    pub public_key: Vec<u8>,
    /// Auto-generated field.
    pub sig_len: i32,
    /// Auto-generated field.
    pub signature: Vec<u8>,
}

impl ChatSessionUpdate {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let session_uuid = uuid_c::read(reader)?;
        let __buf = reader.read_exact(8)?;
        let expire_time = i64::from_be_bytes([
            __buf[0], __buf[1], __buf[2], __buf[3], __buf[4], __buf[5], __buf[6], __buf[7],
        ]);
        let pk_len = varint::read(reader)?;
        let public_key = reader.read_exact(pk_len as usize)?.to_vec();
        let sig_len = varint::read(reader)?;
        let signature = reader.read_exact(sig_len as usize)?.to_vec();
        Ok(Self {
            session_uuid,
            expire_time,
            pk_len,
            public_key,
            sig_len,
            signature,
        })
    }
}

impl ServerboundPacket for ChatSessionUpdate {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        uuid_c::write(&self.session_uuid, writer)?;
        writer.write_all(&self.expire_time.to_be_bytes())?;
        varint::write(self.pk_len, writer)?;
        writer.write_all(&self.public_key)?;
        varint::write(self.sig_len, writer)?;
        writer.write_all(&self.signature)?;
        Ok(())
    }
}
