//! Packet `client_command` (play/serverbound, id 0x07).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/client_command.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x07;

/// ClientCommand packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct ClientCommand {
    /// Auto-generated field.
    pub action_id: i32,
}

impl ClientCommand {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let action_id = varint::read(reader)?;
        Ok(Self { action_id })
    }
}

impl ServerboundPacket for ClientCommand {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.action_id, writer)?;
        Ok(())
    }
}
