//! Packet `close_window` (play/serverbound, id 0x0C).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/close_window.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x0C;

/// CloseWindow packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct CloseWindow {
    /// Auto-generated field.
    pub window_id: u8,
}

impl CloseWindow {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let window_id = reader.read_exact(1)?[0];
        Ok(Self { window_id })
    }
}

impl ServerboundPacket for CloseWindow {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&[self.window_id])?;
        Ok(())
    }
}
