//! Packet `craft_recipe_request` (play/serverbound, id 0x1B).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/craft_recipe_request.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0x1B;
