//! Packet `craft_recipe_request` (play/serverbound, id 0x1B).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/craft_recipe_request.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x1B;

/// CraftRecipeRequest packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct CraftRecipeRequest {
    /// Auto-generated field.
    pub window_id: i8,
    /// Auto-generated field.
    pub recipe: String,
    /// Auto-generated field.
    pub make_all: bool,
}

impl CraftRecipeRequest {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let __buf = reader.read_exact(1)?;
        let window_id = __buf[0] as i8;
        let recipe = string::read(reader)?;
        let make_all = { let __b = reader.read_exact(1)?[0]; if __b > 1 { return Err(ProtocolError::DecodeError(format!("make_all: {}", __b))); } __b != 0 };
        Ok(Self { window_id, recipe, make_all })
    }
}

impl ServerboundPacket for CraftRecipeRequest {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&[self.window_id as u8])?;
        string::write(&self.recipe, writer)?;
        writer.write_all(&[if self.make_all { 1 } else { 0 }])?;
        Ok(())
    }
}
