//! Packet `custom_payload` (play/serverbound, id 0x0D).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/custom_payload.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x0D;

/// CustomPayload packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct CustomPayload {
    /// Auto-generated field.
    pub channel: String,
    /// Auto-generated field.
    pub data: Vec<u8>,
}

impl CustomPayload {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let channel = string::read(reader)?;
        let data = reader.read_exact(reader.remaining())?.to_vec();
        Ok(Self { channel, data })
    }
}

impl ServerboundPacket for CustomPayload {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        string::write(&self.channel, writer)?;
        writer.write_all(&self.data)?;
        Ok(())
    }
}
