//! Packet `displayed_recipe` (play/serverbound, id 0x22).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/displayed_recipe.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x22;

/// DisplayedRecipe packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct DisplayedRecipe {
    /// Auto-generated field.
    pub recipe_id: String,
}

impl DisplayedRecipe {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let recipe_id = string::read(reader)?;
        Ok(Self { recipe_id })
    }
}

impl ServerboundPacket for DisplayedRecipe {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        string::write(&self.recipe_id, writer)?;
        Ok(())
    }
}
