//! Packet `edit_book` (play/serverbound, id 0x0E).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/edit_book.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x0E;

/// EditBook packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct EditBook {
    /// Auto-generated field.
    pub hand: i32,
    /// Auto-generated field.
    pub n: i32,
    /// Auto-generated field.
    pub pages: Vec<String>,
    /// Auto-generated field.
    pub present: u8,
    /// Auto-generated field.
    pub title: Option<String>,
}

impl EditBook {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let hand = varint::read(reader)?;
        let n = varint::read(reader)?;
        let pages = { let mut __v: Vec<String> = Vec::with_capacity(n as usize); for _ in 0..n { __v.push(string::read(reader)?); } __v };
        let present = reader.read_exact(1)?[0];
        let title = match present {
            0 => None,
            1 => Some(string::read(reader)?),
            other => return Err(ProtocolError::DecodeError(format!("title.present: {}", other))),
        };
        Ok(Self { hand, n, pages, present, title })
    }
}

impl ServerboundPacket for EditBook {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.hand, writer)?;
        varint::write(self.n, writer)?;
        match &self.title {
            None => writer.write_all(&[0])?,
            Some(v) => {
                writer.write_all(&[1])?;
                string::write(v, writer)?;
            }
        }
        Ok(())
    }
}
