//! Packet `edit_book` (play/serverbound, id 0x0E).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/edit_book.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0x0E;
