//! Packet `enchant_item` (play/serverbound, id 0x0A).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/enchant_item.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x0A;

/// EnchantItem packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct EnchantItem {
    /// Auto-generated field.
    pub wid: i8,
    /// Auto-generated field.
    pub en: i8,
}

impl EnchantItem {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let __buf = reader.read_exact(2)?;
        let wid = __buf[0] as i8;
        let en = __buf[1] as i8;
        Ok(Self { wid, en })
    }
}

impl ServerboundPacket for EnchantItem {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&[self.wid as u8])?;
        writer.write_all(&[self.en as u8])?;
        Ok(())
    }
}
