//! Packet `entity_action` (play/serverbound, id 0x1E).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/entity_action.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x1E;

/// EntityAction packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct EntityAction {
    /// Auto-generated field.
    pub entity_id: i32,
    /// Auto-generated field.
    pub action_id: i32,
    /// Auto-generated field.
    pub jump_boost: i32,
}

impl EntityAction {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let entity_id = varint::read(reader)?;
        let action_id = varint::read(reader)?;
        let jump_boost = varint::read(reader)?;
        Ok(Self {
            entity_id,
            action_id,
            jump_boost,
        })
    }
}

impl ServerboundPacket for EntityAction {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.entity_id, writer)?;
        varint::write(self.action_id, writer)?;
        varint::write(self.jump_boost, writer)?;
        Ok(())
    }
}
