//! Packet `flying` (play/serverbound, id 0x17).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/flying.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x17;

/// Flying packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct Flying {
    /// Auto-generated field.
    pub on_ground: bool,
}

impl Flying {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let on_ground = { let __b = reader.read_exact(1)?[0]; if __b > 1 { return Err(ProtocolError::DecodeError(format!("on_ground: {}", __b))); } __b != 0 };
        Ok(Self { on_ground })
    }
}

impl ServerboundPacket for Flying {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        Ok::<(), ProtocolError>(())?;
        Ok(())
    }
}
