//! Packet `generate_structure` (play/serverbound, id 0x11).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/generate_structure.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::codec::position;
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x11;

/// GenerateStructure packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct GenerateStructure {
    /// Auto-generated field.
    pub location: (i32, i32, i32),
    /// Auto-generated field.
    pub levels: i32,
    /// Auto-generated field.
    pub keep_jigsaws: bool,
}

impl GenerateStructure {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let location = position::read(reader)?;
        let levels = varint::read(reader)?;
        let keep_jigsaws = { let __b = reader.read_exact(1)?[0]; if __b > 1 { return Err(ProtocolError::DecodeError(format!("keep_jigsaws: {}", __b))); } __b != 0 };
        Ok(Self { location, levels, keep_jigsaws })
    }
}

impl ServerboundPacket for GenerateStructure {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        position::write(&self.location, writer)?;
        varint::write(self.levels, writer)?;
        Ok(())
    }
}
