//! Packet `generate_structure` (play/serverbound, id 0x11).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/generate_structure.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0x11;
