//! Packet `keep_alive` (play/serverbound, id 0x12).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/keep_alive.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x12;

/// KeepAlive packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct KeepAlive {
    /// Auto-generated field.
    pub keep_alive_id: i64,
}

impl KeepAlive {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let __buf = reader.read_exact(8)?;
        let keep_alive_id = i64::from_be_bytes([__buf[0],__buf[1],__buf[2],__buf[3],__buf[4],__buf[5],__buf[6],__buf[7]]);
        Ok(Self { keep_alive_id })
    }
}

impl ServerboundPacket for KeepAlive {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&self.keep_alive_id.to_be_bytes())?;
        Ok(())
    }
}
