//! Packet `keep_alive` (play/serverbound, id 0x12).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/keep_alive.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x12;

/// KeepAlive packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct KeepAlive {
    /// Auto-generated field.
    pub keep_alive_id: i64,
}

impl KeepAlive {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let keep_alive_id = i64::from_be_bytes({
            let _b = reader.read_exact(8)?;
            [_b[0], _b[1], _b[2], _b[3], _b[4], _b[5], _b[6], _b[7]]
        });
        Ok(Self { keep_alive_id })
    }
}

impl ServerboundPacket for KeepAlive {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&self.keep_alive_id.to_be_bytes())?;
        Ok(())
    }
}
