//! Packet `lock_difficulty` (play/serverbound, id 0x13).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/lock_difficulty.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x13;

/// LockDifficulty packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct LockDifficulty {
    /// Auto-generated field.
    pub locked: bool,
}

impl LockDifficulty {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let locked = { let __b = reader.read_exact(1)?[0]; if __b > 1 { return Err(ProtocolError::DecodeError(format!("locked: {}", __b))); } __b != 0 };
        Ok(Self { locked })
    }
}

impl ServerboundPacket for LockDifficulty {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&[if self.locked { 1 } else { 0 }])?;
        Ok(())
    }
}
