//! Packet `message_acknowledgement` (play/serverbound, id 0x03).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/message_acknowledgement.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x03;

/// MessageAcknowledgement packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct MessageAcknowledgement {
    /// Auto-generated field.
    pub count: i32,
}

impl MessageAcknowledgement {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let count = varint::read(reader)?;
        Ok(Self { count })
    }
}

impl ServerboundPacket for MessageAcknowledgement {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.count, writer)?;
        Ok(())
    }
}
