//! Packet `pick_item` (play/serverbound, id 0x1A).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/pick_item.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x1A;

/// PickItem packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct PickItem {
    /// Auto-generated field.
    pub slot: i32,
}

impl PickItem {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let slot = varint::read(reader)?;
        Ok(Self { slot })
    }
}

impl ServerboundPacket for PickItem {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.slot, writer)?;
        Ok(())
    }
}
