//! Packet `position` (play/serverbound, id 0x14).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/position.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x14;

/// Position packet body (auto-generated).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct Position {
    /// Auto-generated field.
    pub x: f64,
    /// Auto-generated field.
    pub y: f64,
    /// Auto-generated field.
    pub z: f64,
    /// Auto-generated field.
    pub on_ground: bool,
}

impl Position {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let __buf = reader.read_exact(24)?;
        let x = f64::from_be_bytes([__buf[0],__buf[1],__buf[2],__buf[3],__buf[4],__buf[5],__buf[6],__buf[7]]);
        let y = f64::from_be_bytes([__buf[8],__buf[9],__buf[10],__buf[11],__buf[12],__buf[13],__buf[14],__buf[15]]);
        let z = f64::from_be_bytes([__buf[16],__buf[17],__buf[18],__buf[19],__buf[20],__buf[21],__buf[22],__buf[23]]);
        let on_ground = { let __b = reader.read_exact(1)?[0]; if __b > 1 { return Err(ProtocolError::DecodeError(format!("on_ground: {}", __b))); } __b != 0 };
        Ok(Self { x, y, z, on_ground })
    }
}

impl ServerboundPacket for Position {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&self.x.to_be_bytes())?;
        writer.write_all(&self.y.to_be_bytes())?;
        writer.write_all(&self.z.to_be_bytes())?;
        Ok(())
    }
}
