//! Packet `position` (play/serverbound, id 0x14).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/position.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0x14;
