//! Packet `query_block_nbt` (play/serverbound, id 0x01).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/query_block_nbt.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::codec::position;
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x01;

/// QueryBlockNbt packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct QueryBlockNbt {
    /// Auto-generated field.
    pub transaction_id: i32,
    /// Auto-generated field.
    pub location: (i32, i32, i32),
}

impl QueryBlockNbt {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let transaction_id = varint::read(reader)?;
        let location = position::read(reader)?;
        Ok(Self { transaction_id, location })
    }
}

impl ServerboundPacket for QueryBlockNbt {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.transaction_id, writer)?;
        position::write(&self.location, writer)?;
        Ok(())
    }
}
