//! Packet `recipe_book` (play/serverbound, id 0x21).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/recipe_book.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x21;

/// RecipeBook packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct RecipeBook {
    /// Auto-generated field.
    pub book_id: i32,
    /// Auto-generated field.
    pub book_open: bool,
    /// Auto-generated field.
    pub filter_active: bool,
}

impl RecipeBook {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let book_id = varint::read(reader)?;
        let book_open = { let __b = reader.read_exact(1)?[0]; if __b > 1 { return Err(ProtocolError::DecodeError(format!("bool: {}", __b))); } __b != 0 };
        let filter_active = { let __b = reader.read_exact(1)?[0]; if __b > 1 { return Err(ProtocolError::DecodeError(format!("bool: {}", __b))); } __b != 0 };
        Ok(Self { book_id, book_open, filter_active })
    }
}

impl ServerboundPacket for RecipeBook {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.book_id, writer)?;
        Ok(())
    }
}
