//! Packet `select_trade` (play/serverbound, id 0x26).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/select_trade.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x26;

/// SelectTrade packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct SelectTrade {
    /// Auto-generated field.
    pub slot: i32,
}

impl SelectTrade {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let slot = varint::read(reader)?;
        Ok(Self { slot })
    }
}

impl ServerboundPacket for SelectTrade {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.slot, writer)?;
        Ok(())
    }
}
