//! Packet `set_difficulty` (play/serverbound, id 0x02).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/set_difficulty.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x02;

/// SetDifficulty packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct SetDifficulty {
    /// Auto-generated field.
    pub new_difficulty: u8,
}

impl SetDifficulty {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let new_difficulty = reader.read_exact(1)?[0];
        Ok(Self { new_difficulty })
    }
}

impl ServerboundPacket for SetDifficulty {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&[self.new_difficulty])?;
        Ok(())
    }
}
