//! Packet `set_beacon_effect` (play/serverbound, id 0x27).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/set_beacon_effect.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x27;

/// SetBeaconEffect packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct SetBeaconEffect {
    /// Auto-generated field.
    pub primary_effect: Option<i32>,
    /// Auto-generated field.
    pub secondary_effect: Option<i32>,
}

impl SetBeaconEffect {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let primary_effect = { let __p = reader.read_exact(1)?[0]; match __p { 0 => None, 1 => Some(varint::read(reader)?), _ => return Err(ProtocolError::DecodeError(format!("opt_varint: {}", __p))) } };
        let secondary_effect = { let __p = reader.read_exact(1)?[0]; match __p { 0 => None, 1 => Some(varint::read(reader)?), _ => return Err(ProtocolError::DecodeError(format!("opt_varint: {}", __p))) } };
        Ok(Self { primary_effect, secondary_effect })
    }
}

impl ServerboundPacket for SetBeaconEffect {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        Ok::<(), ProtocolError>(())?;
        Ok(())
    }
}
