//! Packet `set_creative_slot` (play/serverbound, id 0x2B).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/set_creative_slot.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x2B;

/// SetCreativeSlot packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct SetCreativeSlot {
    /// Auto-generated field.
    pub slot_index: i16,
}

impl SetCreativeSlot {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let __buf = reader.read_exact(2)?;
        let slot_index = i16::from_be_bytes([__buf[0],__buf[1]]);
        Ok(Self { slot_index })
    }
}

impl ServerboundPacket for SetCreativeSlot {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&self.slot_index.to_be_bytes())?;
        Ok(())
    }
}
