//! Packet `settings` (play/serverbound, id 0x08).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/settings.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x08;

/// Settings packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct Settings {
    /// Auto-generated field.
    pub locale: String,
    /// Auto-generated field.
    pub view_distance: i8,
    /// Auto-generated field.
    pub chat_flags: i32,
    /// Auto-generated field.
    pub chat_colors: bool,
    /// Auto-generated field.
    pub skin_parts: u8,
    /// Auto-generated field.
    pub main_hand: i32,
    /// Auto-generated field.
    pub enable_text_filtering: bool,
    /// Auto-generated field.
    pub enable_server_listing: bool,
}

impl Settings {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let locale = string::read(reader)?;
        let __buf = reader.read_exact(1)?;
        let view_distance = __buf[0] as i8;
        let chat_flags = varint::read(reader)?;
        let chat_colors = { let __b = reader.read_exact(1)?[0]; if __b > 1 { return Err(ProtocolError::DecodeError(format!("bool: {}", __b))); } __b != 0 };
        let __buf = reader.read_exact(1)?;
        let skin_parts = __buf[0];
        let main_hand = varint::read(reader)?;
        let enable_text_filtering = { let __b = reader.read_exact(1)?[0]; if __b > 1 { return Err(ProtocolError::DecodeError(format!("bool: {}", __b))); } __b != 0 };
        let enable_server_listing = { let __b = reader.read_exact(1)?[0]; if __b > 1 { return Err(ProtocolError::DecodeError(format!("bool: {}", __b))); } __b != 0 };
        Ok(Self { locale, view_distance, chat_flags, chat_colors, skin_parts, main_hand, enable_text_filtering, enable_server_listing })
    }
}

impl ServerboundPacket for Settings {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        string::write(&self.locale, writer)?;
        writer.write_all(&[self.view_distance as u8])?;
        varint::write(self.chat_flags, writer)?;
        writer.write_all(&[self.skin_parts])?;
        varint::write(self.main_hand, writer)?;
        Ok(())
    }
}
