//! Packet `spectate` (play/serverbound, id 0x30).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/spectate.py.

use crate::codec::uuid_codec::{self as uuid_c, Uuid};
use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x30;

/// Spectate packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct Spectate {
    /// Auto-generated field.
    pub target: Uuid,
}

impl Spectate {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let target = uuid_c::read(reader)?;
        Ok(Self { target })
    }
}

impl ServerboundPacket for Spectate {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        uuid_c::write(&self.target, writer)?;
        Ok(())
    }
}
