//! Packet `steer_vehicle` (play/serverbound, id 0x1F).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/steer_vehicle.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x1F;

/// SteerVehicle packet body (auto-generated).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct SteerVehicle {
    /// Auto-generated field.
    pub sideways: f32,
    /// Auto-generated field.
    pub forward: f32,
    /// Auto-generated field.
    pub flags: u8,
}

impl SteerVehicle {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let __buf = reader.read_exact(8)?;
        let sideways = f32::from_be_bytes([__buf[0],__buf[1],__buf[2],__buf[3]]);
        let forward = f32::from_be_bytes([__buf[4],__buf[5],__buf[6],__buf[7]]);
        let flags = reader.read_exact(1)?[0];
        Ok(Self { sideways, forward, flags })
    }
}

impl ServerboundPacket for SteerVehicle {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&self.sideways.to_be_bytes())?;
        writer.write_all(&self.forward.to_be_bytes())?;
        writer.write_all(&[self.flags])?;
        Ok(())
    }
}
