//! Packet `steer_boat` (play/serverbound, id 0x19).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/steer_boat.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0x19;
