//! Packet `steer_boat` (play/serverbound, id 0x19).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/steer_boat.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x19;

/// SteerBoat packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct SteerBoat {
    /// Auto-generated field.
    pub left_paddle: bool,
    /// Auto-generated field.
    pub right_paddle: bool,
}

impl SteerBoat {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let left_paddle = {
            let __b = reader.read_exact(1)?[0];
            if __b > 1 {
                return Err(ProtocolError::DecodeError(format!("bool: {}", __b)));
            }
            __b != 0
        };
        let right_paddle = {
            let __b = reader.read_exact(1)?[0];
            if __b > 1 {
                return Err(ProtocolError::DecodeError(format!("bool: {}", __b)));
            }
            __b != 0
        };
        Ok(Self {
            left_paddle,
            right_paddle,
        })
    }
}

impl ServerboundPacket for SteerBoat {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&[if self.left_paddle { 1 } else { 0 }])?;
        writer.write_all(&[if self.right_paddle { 1 } else { 0 }])?;
        Ok(())
    }
}
