//! Packet `tab_complete` (play/serverbound, id 0x09).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/tab_complete.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x09;

/// TabComplete packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct TabComplete {
    /// Auto-generated field.
    pub transaction_id: i32,
    /// Auto-generated field.
    pub text: String,
}

impl TabComplete {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let transaction_id = varint::read(reader)?;
        let text = string::read(reader)?;
        Ok(Self { transaction_id, text })
    }
}

impl ServerboundPacket for TabComplete {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.transaction_id, writer)?;
        string::write(&self.text, writer)?;
        Ok(())
    }
}
