//! Packet `teleport_confirm` (play/serverbound, id 0x00).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/teleport_confirm.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x00;

/// TeleportConfirm packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct TeleportConfirm {
    /// Auto-generated field.
    pub teleport_id: i32,
}

impl TeleportConfirm {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let teleport_id = varint::read(reader)?;
        Ok(Self { teleport_id })
    }
}

impl ServerboundPacket for TeleportConfirm {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.teleport_id, writer)?;
        Ok(())
    }
}
