//! Packet `update_command_block` (play/serverbound, id 0x29).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/update_command_block.py.

use crate::codec::position;
use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x29;

/// UpdateCommandBlock packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct UpdateCommandBlock {
    /// Auto-generated field.
    pub location: (i32, i32, i32),
    /// Auto-generated field.
    pub command: String,
    /// Auto-generated field.
    pub mode: i32,
    /// Auto-generated field.
    pub flags: u8,
}

impl UpdateCommandBlock {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let location = position::read(reader)?;
        let command = string::read(reader)?;
        let mode = varint::read(reader)?;
        let flags = reader.read_exact(1)?[0];
        Ok(Self {
            location,
            command,
            mode,
            flags,
        })
    }
}

impl ServerboundPacket for UpdateCommandBlock {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        position::write(&self.location, writer)?;
        string::write(&self.command, writer)?;
        varint::write(self.mode, writer)?;
        writer.write_all(&[self.flags])?;
        Ok(())
    }
}
