//! Packet `update_jigsaw_block` (play/serverbound, id 0x2C).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/update_jigsaw_block.py.

use crate::codec::position;
use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x2C;

/// UpdateJigsawBlock packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct UpdateJigsawBlock {
    /// Auto-generated field.
    pub location: (i32, i32, i32),
    /// Auto-generated field.
    pub name: String,
    /// Auto-generated field.
    pub target: String,
    /// Auto-generated field.
    pub pool: String,
    /// Auto-generated field.
    pub final_state: String,
    /// Auto-generated field.
    pub joint_type: String,
}

impl UpdateJigsawBlock {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let location = position::read(reader)?;
        let name = string::read(reader)?;
        let target = string::read(reader)?;
        let pool = string::read(reader)?;
        let final_state = string::read(reader)?;
        let joint_type = string::read(reader)?;
        Ok(Self {
            location,
            name,
            target,
            pool,
            final_state,
            joint_type,
        })
    }
}

impl ServerboundPacket for UpdateJigsawBlock {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        position::write(&self.location, writer)?;
        string::write(&self.name, writer)?;
        string::write(&self.target, writer)?;
        string::write(&self.pool, writer)?;
        string::write(&self.final_state, writer)?;
        string::write(&self.joint_type, writer)?;
        Ok(())
    }
}
