//! Packet `update_command_block_minecart` (play/serverbound, id 0x2A).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/update_command_block_minecart.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x2A;

/// UpdateCommandBlockMinecart packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct UpdateCommandBlockMinecart {
    /// Auto-generated field.
    pub entity_id: i32,
    /// Auto-generated field.
    pub command: String,
    /// Auto-generated field.
    pub track_output: bool,
}

impl UpdateCommandBlockMinecart {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let entity_id = varint::read(reader)?;
        let command = string::read(reader)?;
        let track_output = { let __b = reader.read_exact(1)?[0]; if __b > 1 { return Err(ProtocolError::DecodeError(format!("track_output: {}", __b))); } __b != 0 };
        Ok(Self { entity_id, command, track_output })
    }
}

impl ServerboundPacket for UpdateCommandBlockMinecart {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.entity_id, writer)?;
        string::write(&self.command, writer)?;
        writer.write_all(&[if self.track_output { 1 } else { 0 }])?;
        Ok(())
    }
}
