//! Packet `update_sign` (play/serverbound, id 0x2E).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/update_sign.py.

use crate::codec::position;
use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x2E;

/// UpdateSign packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct UpdateSign {
    /// Auto-generated field.
    pub location: (i32, i32, i32),
    /// Auto-generated field.
    pub is_front_text: bool,
    /// Auto-generated field.
    pub line1: String,
    /// Auto-generated field.
    pub line2: String,
    /// Auto-generated field.
    pub line3: String,
    /// Auto-generated field.
    pub line4: String,
}

impl UpdateSign {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let location = position::read(reader)?;
        let is_front_text = {
            let __b = reader.read_exact(1)?[0];
            if __b > 1 {
                return Err(ProtocolError::DecodeError(format!(
                    "is_front_text: {}",
                    __b
                )));
            }
            __b != 0
        };
        let line1 = string::read(reader)?;
        let line2 = string::read(reader)?;
        let line3 = string::read(reader)?;
        let line4 = string::read(reader)?;
        Ok(Self {
            location,
            is_front_text,
            line1,
            line2,
            line3,
            line4,
        })
    }
}

impl ServerboundPacket for UpdateSign {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        position::write(&self.location, writer)?;
        writer.write_all(&[if self.is_front_text { 1 } else { 0 }])?;
        string::write(&self.line1, writer)?;
        string::write(&self.line2, writer)?;
        string::write(&self.line3, writer)?;
        string::write(&self.line4, writer)?;
        Ok(())
    }
}
