//! Packet `update_sign` (play/serverbound, id 0x2E).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/update_sign.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0x2E;
