//! Packet `use_item` (play/serverbound, id 0x32).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/use_item.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Play, Serverbound)`.
pub const PACKET_ID: i32 = 0x32;

/// UseItem packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct UseItem {
    /// Auto-generated field.
    pub hand: i32,
    /// Auto-generated field.
    pub sequence: i32,
}

impl UseItem {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let hand = varint::read(reader)?;
        let sequence = varint::read(reader)?;
        Ok(Self { hand, sequence })
    }
}

impl ServerboundPacket for UseItem {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.hand, writer)?;
        varint::write(self.sequence, writer)?;
        Ok(())
    }
}
