//! Packet `window_click` (play/serverbound, id 0x0B).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/serverbound/window_click.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0x0B;
