//! Packet `encryption_begin` (login/serverbound, id 0x01).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/login/serverbound/encryption_begin.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Login, Serverbound)`.
pub const PACKET_ID: i32 = 0x01;

/// EncryptionBegin packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct EncryptionBegin {
    /// Auto-generated field.
    pub ss_len: i32,
    /// Auto-generated field.
    pub shared_secret: Vec<u8>,
    /// Auto-generated field.
    pub vt_len: i32,
    /// Auto-generated field.
    pub verify_token: Vec<u8>,
}

impl EncryptionBegin {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let ss_len = varint::read(reader)?;
        let shared_secret = reader.read_exact(ss_len as usize)?.to_vec();
        let vt_len = varint::read(reader)?;
        let verify_token = reader.read_exact(vt_len as usize)?.to_vec();
        Ok(Self {
            ss_len,
            shared_secret,
            vt_len,
            verify_token,
        })
    }
}

impl ServerboundPacket for EncryptionBegin {
    fn state(&self) -> ConnectionState {
        ConnectionState::Login
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.ss_len, writer)?;
        writer.write_all(&self.shared_secret)?;
        varint::write(self.vt_len, writer)?;
        writer.write_all(&self.verify_token)?;
        Ok(())
    }
}
