//! Packet `login_plugin_response` (login/serverbound, id 0x02).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/login/serverbound/login_plugin_response.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Login, Serverbound)`.
pub const PACKET_ID: i32 = 0x02;

/// LoginPluginResponse packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct LoginPluginResponse {
    /// Auto-generated field.
    pub message_id: i32,
    /// Auto-generated field.
    pub data: Option<Vec<u8>>,
}

impl LoginPluginResponse {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let message_id = varint::read(reader)?;
        let present = reader.read_exact(1)?[0];
        let data = match present {
            0 => None,
            1 => Some(reader.read_exact(reader.remaining())?.to_vec()),
            other => {
                return Err(ProtocolError::DecodeError(format!(
                    "data.present: {}",
                    other
                )))
            }
        };
        Ok(Self { message_id, data })
    }
}

impl ServerboundPacket for LoginPluginResponse {
    fn state(&self) -> ConnectionState {
        ConnectionState::Login
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.message_id, writer)?;
        match &self.data {
            None => writer.write_all(&[0])?,
            Some(v) => {
                writer.write_all(&[1])?;
            }
        }
        Ok(())
    }
}
