//! Packet `login_start` (login/serverbound, id 0x00).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/login/serverbound/login_start.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::codec::uuid_codec::{self as uuid_c, Uuid};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Login, Serverbound)`.
pub const PACKET_ID: i32 = 0x00;

/// LoginStart packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct LoginStart {
    /// Auto-generated field.
    pub username: String,
    /// Auto-generated field.
    pub player_uuid: Option<Uuid>,
}

impl LoginStart {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let username = string::read(reader)?;
        let present = reader.read_exact(1)?[0];
        let player_uuid = match present {
            0 => None,
            1 => Some(uuid_c::read(reader)?),
            other => return Err(ProtocolError::DecodeError(format!("player_uuid.present: {}", other))),
        };
        Ok(Self { username, player_uuid })
    }
}

impl ServerboundPacket for LoginStart {
    fn state(&self) -> ConnectionState { ConnectionState::Login }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        string::write(&self.username, writer)?;
        match &self.player_uuid {
            None => writer.write_all(&[0])?,
            Some(v) => {
                writer.write_all(&[1])?;
                uuid_c::write(v, writer)?;
            }
        }
        Ok(())
    }
}
