//! Packet `login_plugin_response` (login/serverbound, id 0x02).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/login/serverbound/login_plugin_response.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0x02;
