//! Packet `compress` (login/clientbound, id 0x03).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/login/clientbound/compress.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Login, Clientbound)`.
pub const PACKET_ID: i32 = 0x03;

/// Compress packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct Compress {
    /// Auto-generated field.
    pub threshold: i32,
}

impl Compress {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let threshold = varint::read(reader)?;
        Ok(Self { threshold })
    }
}

impl ClientboundPacket for Compress {
    fn state(&self) -> ConnectionState {
        ConnectionState::Login
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.threshold, writer)?;
        Ok(())
    }
}
