//! Packet `disconnect` (login/clientbound, id 0x00).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/login/clientbound/disconnect.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Login, Clientbound)`.
pub const PACKET_ID: i32 = 0x00;

/// Disconnect packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct Disconnect {
    /// Auto-generated field.
    pub reason: String,
}

impl Disconnect {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let reason = string::read(reader)?;
        Ok(Self { reason })
    }
}

impl ClientboundPacket for Disconnect {
    fn state(&self) -> ConnectionState {
        ConnectionState::Login
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        string::write(&self.reason, writer)?;
        Ok(())
    }
}
