//! Packet `encryption_begin` (login/clientbound, id 0x01).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/login/clientbound/encryption_begin.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0x01;
