//! Packet `encryption_begin` (login/clientbound, id 0x01).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/login/clientbound/encryption_begin.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Login, Clientbound)`.
pub const PACKET_ID: i32 = 0x01;

/// EncryptionBegin packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct EncryptionBegin {
    /// Auto-generated field.
    pub server_id: String,
    /// Auto-generated field.
    pub pk_len: i32,
    /// Auto-generated field.
    pub public_key: Vec<u8>,
    /// Auto-generated field.
    pub vt_len: i32,
    /// Auto-generated field.
    pub verify_token: Vec<u8>,
}

impl EncryptionBegin {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let server_id = string::read(reader)?;
        let pk_len = varint::read(reader)?;
        let public_key = reader.read_exact(pk_len as usize)?.to_vec();
        let vt_len = varint::read(reader)?;
        let verify_token = reader.read_exact(vt_len as usize)?.to_vec();
        Ok(Self {
            server_id,
            pk_len,
            public_key,
            vt_len,
            verify_token,
        })
    }
}

impl ClientboundPacket for EncryptionBegin {
    fn state(&self) -> ConnectionState {
        ConnectionState::Login
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        string::write(&self.server_id, writer)?;
        varint::write(self.pk_len, writer)?;
        writer.write_all(&self.public_key)?;
        varint::write(self.vt_len, writer)?;
        writer.write_all(&self.verify_token)?;
        Ok(())
    }
}
