//! Packet `login_plugin_request` (login/clientbound, id 0x04).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/login/clientbound/login_plugin_request.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Login, Clientbound)`.
pub const PACKET_ID: i32 = 0x04;

/// LoginPluginRequest packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct LoginPluginRequest {
    /// Auto-generated field.
    pub message_id: i32,
    /// Auto-generated field.
    pub channel: String,
    /// Auto-generated field.
    pub data: Vec<u8>,
}

impl LoginPluginRequest {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let message_id = varint::read(reader)?;
        let channel = string::read(reader)?;
        let data = reader.read_exact(reader.remaining())?.to_vec();
        Ok(Self {
            message_id,
            channel,
            data,
        })
    }
}

impl ClientboundPacket for LoginPluginRequest {
    fn state(&self) -> ConnectionState {
        ConnectionState::Login
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.message_id, writer)?;
        string::write(&self.channel, writer)?;
        writer.write_all(&self.data)?;
        Ok(())
    }
}
