//! Packet `login_plugin_request` (login/clientbound, id 0x04).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/login/clientbound/login_plugin_request.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0x04;
