//! Packet `abilities` (play/clientbound, id 0x34).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/abilities.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x34;

/// Abilities packet body (auto-generated).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct Abilities {
    /// Auto-generated field.
    pub flags: i8,
    /// Auto-generated field.
    pub fly: f32,
    /// Auto-generated field.
    pub walk: f32,
}

impl Abilities {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let __buf = reader.read_exact(1)?;
        let flags = __buf[0] as i8;
        let __buf = reader.read_exact(8)?;
        let fly = f32::from_be_bytes([__buf[0],__buf[1],__buf[2],__buf[3]]);
        let walk = f32::from_be_bytes([__buf[4],__buf[5],__buf[6],__buf[7]]);
        Ok(Self { flags, fly, walk })
    }
}

impl ClientboundPacket for Abilities {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&[self.flags as u8])?;
        writer.write_all(&self.fly.to_be_bytes())?;
        writer.write_all(&self.walk.to_be_bytes())?;
        Ok(())
    }
}
