//! Packet `acknowledge_player_digging` (play/clientbound, id 0x06).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/acknowledge_player_digging.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x06;

/// AcknowledgePlayerDigging packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct AcknowledgePlayerDigging {
    /// Auto-generated field.
    pub sequence_id: i32,
}

impl AcknowledgePlayerDigging {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let sequence_id = varint::read(reader)?;
        Ok(Self { sequence_id })
    }
}

impl ClientboundPacket for AcknowledgePlayerDigging {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.sequence_id, writer)?;
        Ok(())
    }
}
