//! Packet `advancements` (play/clientbound, id 0x69).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/advancements.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x69;

/// Advancements packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct Advancements {
    /// Auto-generated field.
    pub payload: Vec<u8>,
}

impl Advancements {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let payload = reader.read_exact(reader.remaining())?.to_vec();
        Ok(Self { payload })
    }
}

impl ClientboundPacket for Advancements {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&self.payload)?;
        Ok(())
    }
}
