//! Packet `animation` (play/clientbound, id 0x04).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/animation.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x04;

/// Animation packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct Animation {
    /// Auto-generated field.
    pub entity_id: i32,
    /// Auto-generated field.
    pub animation: u8,
}

impl Animation {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let entity_id = varint::read(reader)?;
        let animation = reader.read_exact(1)?[0];
        Ok(Self { entity_id, animation })
    }
}

impl ClientboundPacket for Animation {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.entity_id, writer)?;
        Ok(())
    }
}
