//! Packet `attach_entity` (play/clientbound, id 0x53).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/attach_entity.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x53;

/// AttachEntity packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct AttachEntity {
    /// Auto-generated field.
    pub eid: i32,
    /// Auto-generated field.
    pub vid: i32,
}

impl AttachEntity {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let __buf = reader.read_exact(8)?;
        let eid = i32::from_be_bytes([__buf[0],__buf[1],__buf[2],__buf[3]]);
        let vid = i32::from_be_bytes([__buf[4],__buf[5],__buf[6],__buf[7]]);
        Ok(Self { eid, vid })
    }
}

impl ClientboundPacket for AttachEntity {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&self.eid.to_be_bytes())?;
        writer.write_all(&self.vid.to_be_bytes())?;
        Ok(())
    }
}
