//! Packet `block_break_animation` (play/clientbound, id 0x07).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/block_break_animation.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::codec::position;
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x07;

/// BlockBreakAnimation packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct BlockBreakAnimation {
    /// Auto-generated field.
    pub eid: i32,
    /// Auto-generated field.
    pub loc: (i32, i32, i32),
    /// Auto-generated field.
    pub stage: i8,
}

impl BlockBreakAnimation {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let eid = varint::read(reader)?;
        let loc = position::read(reader)?;
        let __buf = reader.read_exact(1)?;
        let stage = __buf[0] as i8;
        Ok(Self { eid, loc, stage })
    }
}

impl ClientboundPacket for BlockBreakAnimation {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.eid, writer)?;
        position::write(&self.loc, writer)?;
        writer.write_all(&[self.stage as u8])?;
        Ok(())
    }
}
