//! Packet `block_action` (play/clientbound, id 0x09).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/block_action.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0x09;
