//! Packet `block_change` (play/clientbound, id 0x0A).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/block_change.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::codec::position;
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x0A;

/// BlockChange packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct BlockChange {
    /// Auto-generated field.
    pub loc: (i32, i32, i32),
    /// Auto-generated field.
    pub bid: i32,
}

impl BlockChange {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let loc = position::read(reader)?;
        let bid = varint::read(reader)?;
        Ok(Self { loc, bid })
    }
}

impl ClientboundPacket for BlockChange {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        position::write(&self.loc, writer)?;
        varint::write(self.bid, writer)?;
        Ok(())
    }
}
