//! Packet `block_break_animation` (play/clientbound, id 0x07).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/block_break_animation.py.

use crate::codec::position;
use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x07;

/// BlockBreakAnimation packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct BlockBreakAnimation {
    /// Auto-generated field.
    pub entity_id: i32,
    /// Auto-generated field.
    pub location: (i32, i32, i32),
    /// Auto-generated field.
    pub destroy_stage: i8,
}

impl BlockBreakAnimation {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let entity_id = varint::read(reader)?;
        let location = position::read(reader)?;
        let __buf = reader.read_exact(1)?;
        let destroy_stage = __buf[0] as i8;
        Ok(Self {
            entity_id,
            location,
            destroy_stage,
        })
    }
}

impl ClientboundPacket for BlockBreakAnimation {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.entity_id, writer)?;
        position::write(&self.location, writer)?;
        writer.write_all(&[self.destroy_stage as u8])?;
        Ok(())
    }
}
