//! Packet `block_action` (play/clientbound, id 0x09).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/block_action.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::codec::position;
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x09;

/// BlockAction packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct BlockAction {
    /// Auto-generated field.
    pub location: (i32, i32, i32),
    /// Auto-generated field.
    pub byte1: u8,
    /// Auto-generated field.
    pub byte2: u8,
    /// Auto-generated field.
    pub block_type: i32,
}

impl BlockAction {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let location = position::read(reader)?;
        let byte1 = reader.read_exact(1)?[0];
        let byte2 = reader.read_exact(1)?[0];
        let block_type = varint::read(reader)?;
        Ok(Self { location, byte1, byte2, block_type })
    }
}

impl ClientboundPacket for BlockAction {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        position::write(&self.location, writer)?;
        varint::write(self.block_type, writer)?;
        Ok(())
    }
}
