//! Packet `boss_bar` (play/clientbound, id 0x0B).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/boss_bar.py.

use crate::codec::uuid_codec::{self as uuid_c, Uuid};
use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x0B;

/// BossBar packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct BossBar {
    /// Auto-generated field.
    pub bar_id: Uuid,
    /// Auto-generated field.
    pub action: i32,
    /// Auto-generated field.
    pub payload: Vec<u8>,
}

impl BossBar {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let bar_id = uuid_c::read(reader)?;
        let action = varint::read(reader)?;
        let payload = reader.read_exact(reader.remaining())?.to_vec();
        Ok(Self {
            bar_id,
            action,
            payload,
        })
    }
}

impl ClientboundPacket for BossBar {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        uuid_c::write(&self.bar_id, writer)?;
        varint::write(self.action, writer)?;
        writer.write_all(&self.payload)?;
        Ok(())
    }
}
