//! Packet `camera` (play/clientbound, id 0x4C).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/camera.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x4C;

/// Camera packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct Camera {
    /// Auto-generated field.
    pub camera_id: i32,
}

impl Camera {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let camera_id = varint::read(reader)?;
        Ok(Self { camera_id })
    }
}

impl ClientboundPacket for Camera {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.camera_id, writer)?;
        Ok(())
    }
}
