//! Packet `chat_suggestions` (play/clientbound, id 0x16).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/chat_suggestions.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x16;

/// ChatSuggestions packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct ChatSuggestions {
    /// Auto-generated field.
    pub action: i32,
    /// Auto-generated field.
    pub n: i32,
    /// Auto-generated field.
    pub entries: Vec<String>,
}

impl ChatSuggestions {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let action = varint::read(reader)?;
        let n = varint::read(reader)?;
        let entries = {
            let mut __v: Vec<String> = Vec::with_capacity(n as usize);
            for _ in 0..n {
                __v.push(string::read(reader)?);
            }
            __v
        };
        Ok(Self { action, n, entries })
    }
}

impl ClientboundPacket for ChatSuggestions {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.action, writer)?;
        varint::write(self.n, writer)?;
        Ok(())
    }
}
