//! Packet `chat_suggestions` (play/clientbound, id 0x16).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/chat_suggestions.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0x16;
