//! Packet `clear_titles` (play/clientbound, id 0x0E).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/clear_titles.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x0E;

/// ClearTitles packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct ClearTitles {
    /// Auto-generated field.
    pub reset: bool,
}

impl ClearTitles {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let reset = {
            let __b = reader.read_exact(1)?[0];
            if __b > 1 {
                return Err(ProtocolError::DecodeError(format!("reset: {}", __b)));
            }
            __b != 0
        };
        Ok(Self { reset })
    }
}

impl ClientboundPacket for ClearTitles {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&[if self.reset { 1 } else { 0 }])?;
        Ok(())
    }
}
