//! Packet `collect` (play/clientbound, id 0x67).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/collect.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x67;

/// Collect packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct Collect {
    /// Auto-generated field.
    pub collected_entity_id: i32,
    /// Auto-generated field.
    pub collector_entity_id: i32,
    /// Auto-generated field.
    pub pickup_item_count: i32,
}

impl Collect {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let collected_entity_id = varint::read(reader)?;
        let collector_entity_id = varint::read(reader)?;
        let pickup_item_count = varint::read(reader)?;
        Ok(Self { collected_entity_id, collector_entity_id, pickup_item_count })
    }
}

impl ClientboundPacket for Collect {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.collected_entity_id, writer)?;
        varint::write(self.collector_entity_id, writer)?;
        varint::write(self.pickup_item_count, writer)?;
        Ok(())
    }
}
