//! Packet `collect` (play/clientbound, id 0x67).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/collect.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x67;

/// Collect packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct Collect {
    /// Auto-generated field.
    pub cd: i32,
    /// Auto-generated field.
    pub cr: i32,
    /// Auto-generated field.
    pub cnt: i32,
}

impl Collect {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let cd = varint::read(reader)?;
        let cr = varint::read(reader)?;
        let cnt = varint::read(reader)?;
        Ok(Self { cd, cr, cnt })
    }
}

impl ClientboundPacket for Collect {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.cd, writer)?;
        varint::write(self.cr, writer)?;
        varint::write(self.cnt, writer)?;
        Ok(())
    }
}
