//! Packet `craft_progress_bar` (play/clientbound, id 0x13).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/craft_progress_bar.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x13;

/// CraftProgressBar packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct CraftProgressBar {
    /// Auto-generated field.
    pub window_id: u8,
    /// Auto-generated field.
    pub property: i16,
    /// Auto-generated field.
    pub value: i16,
}

impl CraftProgressBar {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let window_id = reader.read_exact(1)?[0];
        let __buf = reader.read_exact(4)?;
        let property = i16::from_be_bytes([__buf[0],__buf[1]]);
        let value = i16::from_be_bytes([__buf[2],__buf[3]]);
        Ok(Self { window_id, property, value })
    }
}

impl ClientboundPacket for CraftProgressBar {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&self.property.to_be_bytes())?;
        writer.write_all(&self.value.to_be_bytes())?;
        Ok(())
    }
}
