//! Packet `craft_progress_bar` (play/clientbound, id 0x13).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/craft_progress_bar.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0x13;
