//! Packet `craft_recipe_response` (play/clientbound, id 0x33).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/craft_recipe_response.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x33;

/// CraftRecipeResponse packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct CraftRecipeResponse {
    /// Auto-generated field.
    pub wid: i8,
    /// Auto-generated field.
    pub rec: String,
}

impl CraftRecipeResponse {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let __buf = reader.read_exact(1)?;
        let wid = __buf[0] as i8;
        let rec = string::read(reader)?;
        Ok(Self { wid, rec })
    }
}

impl ClientboundPacket for CraftRecipeResponse {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&[self.wid as u8])?;
        string::write(&self.rec, writer)?;
        Ok(())
    }
}
