//! Packet `damage_event` (play/clientbound, id 0x18).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/damage_event.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0x18;
