//! Packet `death_combat_event` (play/clientbound, id 0x38).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/death_combat_event.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x38;

/// DeathCombatEvent packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct DeathCombatEvent {
    /// Auto-generated field.
    pub player_id: i32,
    /// Auto-generated field.
    pub message: String,
}

impl DeathCombatEvent {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let player_id = varint::read(reader)?;
        let message = string::read(reader)?;
        Ok(Self { player_id, message })
    }
}

impl ClientboundPacket for DeathCombatEvent {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.player_id, writer)?;
        string::write(&self.message, writer)?;
        Ok(())
    }
}
