//! Packet `declare_recipes` (play/clientbound, id 0x6D).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/declare_recipes.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x6D;

/// DeclareRecipes packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct DeclareRecipes {
    /// Auto-generated field.
    pub payload: Vec<u8>,
}

impl DeclareRecipes {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let payload = reader.read_exact(reader.remaining())?.to_vec();
        Ok(Self { payload })
    }
}

impl ClientboundPacket for DeclareRecipes {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&self.payload)?;
        Ok(())
    }
}
