//! Packet `difficulty` (play/clientbound, id 0x0C).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/difficulty.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x0C;

/// Difficulty packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct Difficulty {
    /// Auto-generated field.
    pub difficulty: u8,
    /// Auto-generated field.
    pub locked: bool,
}

impl Difficulty {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let difficulty = reader.read_exact(1)?[0];
        let locked = { let __b = reader.read_exact(1)?[0]; if __b > 1 { return Err(ProtocolError::DecodeError(format!("locked: {}", __b))); } __b != 0 };
        Ok(Self { difficulty, locked })
    }
}

impl ClientboundPacket for Difficulty {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&[self.difficulty])?;
        writer.write_all(&[if self.locked { 1 } else { 0 }])?;
        Ok(())
    }
}
