//! Packet `end_combat_event` (play/clientbound, id 0x36).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/end_combat_event.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x36;

/// EndCombatEvent packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct EndCombatEvent {
    /// Auto-generated field.
    pub duration: i32,
}

impl EndCombatEvent {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let duration = varint::read(reader)?;
        Ok(Self { duration })
    }
}

impl ClientboundPacket for EndCombatEvent {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.duration, writer)?;
        Ok(())
    }
}
