//! Packet `enter_combat_event` (play/clientbound, id 0x37).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/enter_combat_event.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x37;

/// EnterCombatEvent packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct EnterCombatEvent {}

impl EnterCombatEvent {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        Ok(Self {})
    }
}

impl ClientboundPacket for EnterCombatEvent {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        Ok::<(), ProtocolError>(())?;
        Ok(())
    }
}
