//! Packet `entity_head_rotation` (play/clientbound, id 0x42).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/entity_head_rotation.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x42;

/// EntityHeadRotation packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct EntityHeadRotation {
    /// Auto-generated field.
    pub eid: i32,
    /// Auto-generated field.
    pub yaw: i8,
}

impl EntityHeadRotation {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let eid = varint::read(reader)?;
        let __buf = reader.read_exact(1)?;
        let yaw = __buf[0] as i8;
        Ok(Self { eid, yaw })
    }
}

impl ClientboundPacket for EntityHeadRotation {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.eid, writer)?;
        writer.write_all(&[self.yaw as u8])?;
        Ok(())
    }
}
