//! Packet `entity_look` (play/clientbound, id 0x2D).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/entity_look.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x2D;

/// EntityLook packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct EntityLook {
    /// Auto-generated field.
    pub entity_id: i32,
    /// Auto-generated field.
    pub yaw: i8,
    /// Auto-generated field.
    pub pitch: i8,
    /// Auto-generated field.
    pub on_ground: bool,
}

impl EntityLook {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let entity_id = varint::read(reader)?;
        let __buf = reader.read_exact(2)?;
        let yaw = __buf[0] as i8;
        let pitch = __buf[1] as i8;
        let on_ground = { let __b = reader.read_exact(1)?[0]; if __b > 1 { return Err(ProtocolError::DecodeError(format!("on_ground: {}", __b))); } __b != 0 };
        Ok(Self { entity_id, yaw, pitch, on_ground })
    }
}

impl ClientboundPacket for EntityLook {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.entity_id, writer)?;
        writer.write_all(&[self.yaw as u8])?;
        writer.write_all(&[self.pitch as u8])?;
        Ok(())
    }
}
