//! Packet `entity_velocity` (play/clientbound, id 0x54).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/entity_velocity.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x54;

/// EntityVelocity packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct EntityVelocity {
    /// Auto-generated field.
    pub entity_id: i32,
    /// Auto-generated field.
    pub vx: i16,
    /// Auto-generated field.
    pub vy: i16,
    /// Auto-generated field.
    pub vz: i16,
}

impl EntityVelocity {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let entity_id = varint::read(reader)?;
        let __buf = reader.read_exact(6)?;
        let vx = i16::from_be_bytes([__buf[0], __buf[1]]);
        let vy = i16::from_be_bytes([__buf[2], __buf[3]]);
        let vz = i16::from_be_bytes([__buf[4], __buf[5]]);
        Ok(Self {
            entity_id,
            vx,
            vy,
            vz,
        })
    }
}

impl ClientboundPacket for EntityVelocity {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.entity_id, writer)?;
        writer.write_all(&self.vx.to_be_bytes())?;
        writer.write_all(&self.vy.to_be_bytes())?;
        writer.write_all(&self.vz.to_be_bytes())?;
        Ok(())
    }
}
