//! Packet `entity_equipment` (play/clientbound, id 0x55).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/entity_equipment.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0x55;
