//! Packet `entity_metadata` (play/clientbound, id 0x52).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/entity_metadata.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x52;

/// EntityMetadata packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct EntityMetadata {
    /// Auto-generated field.
    pub entity_id: i32,
    /// Auto-generated field.
    pub metadata: Vec<u8>,
}

impl EntityMetadata {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let entity_id = varint::read(reader)?;
        let metadata = reader.read_exact(reader.remaining())?.to_vec();
        Ok(Self { entity_id, metadata })
    }
}

impl ClientboundPacket for EntityMetadata {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.entity_id, writer)?;
        writer.write_all(&self.metadata)?;
        Ok(())
    }
}
