//! Packet `entity_metadata` (play/clientbound, id 0x52).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/entity_metadata.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0x52;
