//! Packet `entity_status` (play/clientbound, id 0x1C).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/entity_status.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x1C;

/// EntityStatus packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct EntityStatus {
    /// Auto-generated field.
    pub entity_id: i32,
    /// Auto-generated field.
    pub status: i8,
}

impl EntityStatus {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let __buf = reader.read_exact(4)?;
        let entity_id = i32::from_be_bytes([__buf[0], __buf[1], __buf[2], __buf[3]]);
        let __buf = reader.read_exact(1)?;
        let status = __buf[0] as i8;
        Ok(Self { entity_id, status })
    }
}

impl ClientboundPacket for EntityStatus {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&self.entity_id.to_be_bytes())?;
        writer.write_all(&[self.status as u8])?;
        Ok(())
    }
}
