//! Packet `entity_sound_effect` (play/clientbound, id 0x61).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/entity_sound_effect.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0x61;
