//! Packet `entity_status` (play/clientbound, id 0x1C).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/entity_status.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x1C;

/// EntityStatus packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct EntityStatus {
    /// Auto-generated field.
    pub eid: i32,
    /// Auto-generated field.
    pub st: i8,
}

impl EntityStatus {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let __buf = reader.read_exact(4)?;
        let eid = i32::from_be_bytes([__buf[0],__buf[1],__buf[2],__buf[3]]);
        let __buf = reader.read_exact(1)?;
        let st = __buf[0] as i8;
        Ok(Self { eid, st })
    }
}

impl ClientboundPacket for EntityStatus {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&self.eid.to_be_bytes())?;
        writer.write_all(&[self.st as u8])?;
        Ok(())
    }
}
