//! Packet `entity_effect` (play/clientbound, id 0x6C).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/entity_effect.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::codec::nbt;
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x6C;

/// EntityEffect packet body (auto-generated).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct EntityEffect {
    /// Auto-generated field.
    pub entity_id: i32,
    /// Auto-generated field.
    pub effect_id: i32,
    /// Auto-generated field.
    pub amplifier: i8,
    /// Auto-generated field.
    pub duration: i32,
    /// Auto-generated field.
    pub flags: i8,
    /// Auto-generated field.
    pub present: u8,
    /// Auto-generated field.
    pub factor_codec: Option<crate::codec::nbt::NbtTag>,
}

impl EntityEffect {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let entity_id = varint::read(reader)?;
        let effect_id = varint::read(reader)?;
        let __buf = reader.read_exact(1)?;
        let amplifier = __buf[0] as i8;
        let duration = varint::read(reader)?;
        let __buf = reader.read_exact(1)?;
        let flags = __buf[0] as i8;
        let present = reader.read_exact(1)?[0];
        let factor_codec = match present {
            0 => None,
            1 => nbt::read(reader)?,
            other => return Err(ProtocolError::DecodeError(format!("factor_codec.present: {}", other))),
        };
        Ok(Self { entity_id, effect_id, amplifier, duration, flags, present, factor_codec })
    }
}

impl ClientboundPacket for EntityEffect {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.entity_id, writer)?;
        varint::write(self.effect_id, writer)?;
        writer.write_all(&[self.amplifier as u8])?;
        varint::write(self.duration, writer)?;
        writer.write_all(&[self.flags as u8])?;
        match &self.factor_codec {
            None => writer.write_all(&[0])?,
            Some(v) => {
                writer.write_all(&[1])?;
                nbt::write(Some(v), writer)?;
            }
        }
        Ok(())
    }
}
