//! Packet `entity_destroy` (play/clientbound, id 0x3E).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/entity_destroy.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x3E;

/// EntityDestroy packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct EntityDestroy {
    /// Auto-generated field.
    pub n: i32,
    /// Auto-generated field.
    pub entity_ids: Vec<i32>,
}

impl EntityDestroy {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let n = varint::read(reader)?;
        let entity_ids = { let mut __v: Vec<i32> = Vec::with_capacity(n as usize); for _ in 0..n { __v.push(varint::read(reader)?); } __v };
        Ok(Self { n, entity_ids })
    }
}

impl ClientboundPacket for EntityDestroy {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.n, writer)?;
        Ok(())
    }
}
