//! Packet `entity_destroy` (play/clientbound, id 0x3E).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/entity_destroy.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0x3E;
