//! Packet `entity_teleport` (play/clientbound, id 0x68).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/entity_teleport.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0x68;
