//! Packet `entity_look` (play/clientbound, id 0x2D).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/entity_look.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0x2D;
