//! Packet `entity_head_rotation` (play/clientbound, id 0x42).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/entity_head_rotation.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x42;

/// EntityHeadRotation packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct EntityHeadRotation {
    /// Auto-generated field.
    pub entity_id: i32,
    /// Auto-generated field.
    pub head_yaw: i8,
}

impl EntityHeadRotation {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let entity_id = varint::read(reader)?;
        let __buf = reader.read_exact(1)?;
        let head_yaw = __buf[0] as i8;
        Ok(Self {
            entity_id,
            head_yaw,
        })
    }
}

impl ClientboundPacket for EntityHeadRotation {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.entity_id, writer)?;
        writer.write_all(&[self.head_yaw as u8])?;
        Ok(())
    }
}
