//! Packet `experience` (play/clientbound, id 0x56).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/experience.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x56;

/// Experience packet body (auto-generated).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct Experience {
    /// Auto-generated field.
    pub bar: f32,
    /// Auto-generated field.
    pub lvl: i32,
    /// Auto-generated field.
    pub total: i32,
}

impl Experience {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let __buf = reader.read_exact(4)?;
        let bar = f32::from_be_bytes([__buf[0],__buf[1],__buf[2],__buf[3]]);
        let lvl = varint::read(reader)?;
        let total = varint::read(reader)?;
        Ok(Self { bar, lvl, total })
    }
}

impl ClientboundPacket for Experience {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&self.bar.to_be_bytes())?;
        varint::write(self.lvl, writer)?;
        varint::write(self.total, writer)?;
        Ok(())
    }
}
