//! Packet `face_player` (play/clientbound, id 0x3B).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/face_player.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x3B;

/// FacePlayer packet body (auto-generated).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct FacePlayer {
    /// Auto-generated field.
    pub feet_eyes: i32,
    /// Auto-generated field.
    pub x: f64,
    /// Auto-generated field.
    pub y: f64,
    /// Auto-generated field.
    pub z: f64,
    /// Auto-generated field.
    pub is_entity: bool,
    /// Auto-generated field.
    pub entity_id: Option<i32>,
    /// Auto-generated field.
    pub entity_feet_eyes: Option<String>,
}

impl FacePlayer {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let feet_eyes = varint::read(reader)?;
        let __buf = reader.read_exact(24)?;
        let x = f64::from_be_bytes([__buf[0],__buf[1],__buf[2],__buf[3],__buf[4],__buf[5],__buf[6],__buf[7]]);
        let y = f64::from_be_bytes([__buf[8],__buf[9],__buf[10],__buf[11],__buf[12],__buf[13],__buf[14],__buf[15]]);
        let z = f64::from_be_bytes([__buf[16],__buf[17],__buf[18],__buf[19],__buf[20],__buf[21],__buf[22],__buf[23]]);
        let is_entity = { let __b = reader.read_exact(1)?[0]; if __b > 1 { return Err(ProtocolError::DecodeError(format!("is_entity: {}", __b))); } __b != 0 };
        let mut entity_id: Option<i32> = None;
        let mut entity_feet_eyes: Option<String> = None;
        if is_entity {
            entity_id = Some(varint::read(reader)?);
            entity_feet_eyes = Some(string::read(reader)?);
        }
        Ok(Self { feet_eyes, x, y, z, is_entity, entity_id, entity_feet_eyes })
    }
}

impl ClientboundPacket for FacePlayer {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.feet_eyes, writer)?;
        writer.write_all(&self.x.to_be_bytes())?;
        writer.write_all(&self.y.to_be_bytes())?;
        writer.write_all(&self.z.to_be_bytes())?;
        Ok(())
    }
}
