//! Packet `feature_flags` (play/clientbound, id 0x6B).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/feature_flags.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x6B;

/// FeatureFlags packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct FeatureFlags {
    /// Auto-generated field.
    pub n: i32,
    /// Auto-generated field.
    pub features: Vec<String>,
}

impl FeatureFlags {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let n = varint::read(reader)?;
        let features = { let mut __v: Vec<String> = Vec::with_capacity(n as usize); for _ in 0..n { __v.push(string::read(reader)?); } __v };
        Ok(Self { n, features })
    }
}

impl ClientboundPacket for FeatureFlags {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.n, writer)?;
        Ok(())
    }
}
