//! Packet `feature_flags` (play/clientbound, id 0x6B).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/feature_flags.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0x6B;
