//! Packet `game_state_change` (play/clientbound, id 0x1F).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/game_state_change.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x1F;

/// GameStateChange packet body (auto-generated).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct GameStateChange {
    /// Auto-generated field.
    pub reason: u8,
    /// Auto-generated field.
    pub value: f32,
}

impl GameStateChange {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let reason = reader.read_exact(1)?[0];
        let __buf = reader.read_exact(4)?;
        let value = f32::from_be_bytes([__buf[0],__buf[1],__buf[2],__buf[3]]);
        Ok(Self { reason, value })
    }
}

impl ClientboundPacket for GameStateChange {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&[self.reason])?;
        writer.write_all(&self.value.to_be_bytes())?;
        Ok(())
    }
}
