//! Packet `game_state_change` (play/clientbound, id 0x1F).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/game_state_change.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0x1F;
