//! Packet `held_item_slot` (play/clientbound, id 0x4D).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/held_item_slot.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x4D;

/// HeldItemSlot packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct HeldItemSlot {
    /// Auto-generated field.
    pub slot: i8,
}

impl HeldItemSlot {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let __buf = reader.read_exact(1)?;
        let slot = __buf[0] as i8;
        Ok(Self { slot })
    }
}

impl ClientboundPacket for HeldItemSlot {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&[self.slot as u8])?;
        Ok(())
    }
}
