//! Packet `hide_message` (play/clientbound, id 0x19).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/hide_message.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x19;

/// HideMessage packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct HideMessage {
    /// Auto-generated field.
    pub id: i32,
    /// Auto-generated field.
    pub signature: Option<Vec<u8>>,
}

impl HideMessage {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let id = varint::read(reader)?;
        let mut signature: Option<Vec<u8>> = None;
        if id == 0 {
            signature = Some(reader.read_exact(256)?.to_vec());
        }
        Ok(Self { id, signature })
    }
}

impl ClientboundPacket for HideMessage {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.id, writer)?;
        Ok(())
    }
}
