//! Packet `hide_message` (play/clientbound, id 0x19).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/hide_message.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0x19;
