//! Packet `hurt_animation` (play/clientbound, id 0x21).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/hurt_animation.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x21;

/// HurtAnimation packet body (auto-generated).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct HurtAnimation {
    /// Auto-generated field.
    pub entity_id: i32,
    /// Auto-generated field.
    pub yaw: f32,
}

impl HurtAnimation {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let entity_id = varint::read(reader)?;
        let __buf = reader.read_exact(4)?;
        let yaw = f32::from_be_bytes([__buf[0],__buf[1],__buf[2],__buf[3]]);
        Ok(Self { entity_id, yaw })
    }
}

impl ClientboundPacket for HurtAnimation {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.entity_id, writer)?;
        writer.write_all(&self.yaw.to_be_bytes())?;
        Ok(())
    }
}
