//! Packet `initialize_world_border` (play/clientbound, id 0x22).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/initialize_world_border.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x22;

/// InitializeWorldBorder packet body (auto-generated).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct InitializeWorldBorder {
    /// Auto-generated field.
    pub x: f64,
    /// Auto-generated field.
    pub z: f64,
    /// Auto-generated field.
    pub old_diameter: f64,
    /// Auto-generated field.
    pub new_diameter: f64,
    /// Auto-generated field.
    pub speed: i32,
    /// Auto-generated field.
    pub portal_teleport_boundary: i32,
    /// Auto-generated field.
    pub warning_blocks: i32,
    /// Auto-generated field.
    pub warning_time: i32,
}

impl InitializeWorldBorder {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let __buf = reader.read_exact(32)?;
        let x = f64::from_be_bytes([__buf[0],__buf[1],__buf[2],__buf[3],__buf[4],__buf[5],__buf[6],__buf[7]]);
        let z = f64::from_be_bytes([__buf[8],__buf[9],__buf[10],__buf[11],__buf[12],__buf[13],__buf[14],__buf[15]]);
        let old_diameter = f64::from_be_bytes([__buf[16],__buf[17],__buf[18],__buf[19],__buf[20],__buf[21],__buf[22],__buf[23]]);
        let new_diameter = f64::from_be_bytes([__buf[24],__buf[25],__buf[26],__buf[27],__buf[28],__buf[29],__buf[30],__buf[31]]);
        let speed = varint::read(reader)?;
        let portal_teleport_boundary = varint::read(reader)?;
        let warning_blocks = varint::read(reader)?;
        let warning_time = varint::read(reader)?;
        Ok(Self { x, z, old_diameter, new_diameter, speed, portal_teleport_boundary, warning_blocks, warning_time })
    }
}

impl ClientboundPacket for InitializeWorldBorder {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&self.x.to_be_bytes())?;
        writer.write_all(&self.z.to_be_bytes())?;
        writer.write_all(&self.old_diameter.to_be_bytes())?;
        writer.write_all(&self.new_diameter.to_be_bytes())?;
        varint::write(self.speed, writer)?;
        varint::write(self.portal_teleport_boundary, writer)?;
        varint::write(self.warning_blocks, writer)?;
        varint::write(self.warning_time, writer)?;
        Ok(())
    }
}
