//! Packet `kick_disconnect` (play/clientbound, id 0x1A).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/kick_disconnect.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x1A;

/// KickDisconnect packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct KickDisconnect {
    /// Auto-generated field.
    pub reason: String,
}

impl KickDisconnect {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let reason = string::read(reader)?;
        Ok(Self { reason })
    }
}

impl ClientboundPacket for KickDisconnect {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        string::write(&self.reason, writer)?;
        Ok(())
    }
}
