//! Packet `map` (play/clientbound, id 0x29).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/map.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x29;

/// Map packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct Map {
    /// Auto-generated field.
    pub map_id: i32,
    /// Auto-generated field.
    pub scale: i8,
    /// Auto-generated field.
    pub payload: Vec<u8>,
}

impl Map {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let map_id = varint::read(reader)?;
        let __buf = reader.read_exact(1)?;
        let scale = __buf[0] as i8;
        let payload = reader.read_exact(reader.remaining())?.to_vec();
        Ok(Self {
            map_id,
            scale,
            payload,
        })
    }
}

impl ClientboundPacket for Map {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.map_id, writer)?;
        writer.write_all(&[self.scale as u8])?;
        writer.write_all(&self.payload)?;
        Ok(())
    }
}
