//! Packet `map_chunk` (play/clientbound, id 0x24).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/map_chunk.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x24;

/// MapChunk packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct MapChunk {
    /// Auto-generated field.
    pub chunk_x: i32,
    /// Auto-generated field.
    pub chunk_z: i32,
    /// Auto-generated field.
    pub payload: Vec<u8>,
}

impl MapChunk {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let __buf = reader.read_exact(8)?;
        let chunk_x = i32::from_be_bytes([__buf[0],__buf[1],__buf[2],__buf[3]]);
        let chunk_z = i32::from_be_bytes([__buf[4],__buf[5],__buf[6],__buf[7]]);
        let payload = reader.read_exact(reader.remaining())?.to_vec();
        Ok(Self { chunk_x, chunk_z, payload })
    }
}

impl ClientboundPacket for MapChunk {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&self.chunk_x.to_be_bytes())?;
        writer.write_all(&self.chunk_z.to_be_bytes())?;
        writer.write_all(&self.payload)?;
        Ok(())
    }
}
