//! Packet `multi_block_change` (play/clientbound, id 0x43).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/multi_block_change.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0x43;
