//! Packet `named_entity_spawn` (play/clientbound, id 0x03).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/named_entity_spawn.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::codec::uuid_codec::{self as uuid_c, Uuid};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x03;

/// NamedEntitySpawn packet body (auto-generated).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct NamedEntitySpawn {
    /// Auto-generated field.
    pub entity_id: i32,
    /// Auto-generated field.
    pub player_uuid: Uuid,
    /// Auto-generated field.
    pub x: f64,
    /// Auto-generated field.
    pub y: f64,
    /// Auto-generated field.
    pub z: f64,
    /// Auto-generated field.
    pub yaw: i8,
    /// Auto-generated field.
    pub pitch: i8,
}

impl NamedEntitySpawn {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let entity_id = varint::read(reader)?;
        let player_uuid = uuid_c::read(reader)?;
        let __buf = reader.read_exact(24)?;
        let x = f64::from_be_bytes([__buf[0],__buf[1],__buf[2],__buf[3],__buf[4],__buf[5],__buf[6],__buf[7]]);
        let y = f64::from_be_bytes([__buf[8],__buf[9],__buf[10],__buf[11],__buf[12],__buf[13],__buf[14],__buf[15]]);
        let z = f64::from_be_bytes([__buf[16],__buf[17],__buf[18],__buf[19],__buf[20],__buf[21],__buf[22],__buf[23]]);
        let __buf = reader.read_exact(2)?;
        let yaw = __buf[0] as i8;
        let pitch = __buf[1] as i8;
        Ok(Self { entity_id, player_uuid, x, y, z, yaw, pitch })
    }
}

impl ClientboundPacket for NamedEntitySpawn {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.entity_id, writer)?;
        uuid_c::write(&self.player_uuid, writer)?;
        writer.write_all(&self.x.to_be_bytes())?;
        writer.write_all(&self.y.to_be_bytes())?;
        writer.write_all(&self.z.to_be_bytes())?;
        writer.write_all(&[self.yaw as u8])?;
        writer.write_all(&[self.pitch as u8])?;
        Ok(())
    }
}
