//! Packet `nbt_query_response` (play/clientbound, id 0x66).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/nbt_query_response.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::codec::nbt;
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x66;

/// NbtQueryResponse packet body (auto-generated).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct NbtQueryResponse {
    /// Auto-generated field.
    pub tid: i32,
    /// Auto-generated field.
    pub tag: Option<crate::codec::nbt::NbtTag>,
}

impl NbtQueryResponse {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let tid = varint::read(reader)?;
        let tag = nbt::read(reader)?;
        Ok(Self { tid, tag })
    }
}

impl ClientboundPacket for NbtQueryResponse {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.tid, writer)?;
        nbt::write(self.tag.as_ref(), writer)?;
        Ok(())
    }
}
