//! Packet `open_horse_window` (play/clientbound, id 0x20).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/open_horse_window.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x20;

/// OpenHorseWindow packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct OpenHorseWindow {
    /// Auto-generated field.
    pub window_id: u8,
    /// Auto-generated field.
    pub nb_slots: i32,
    /// Auto-generated field.
    pub entity_id: i32,
}

impl OpenHorseWindow {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let window_id = reader.read_exact(1)?[0];
        let nb_slots = varint::read(reader)?;
        let __buf = reader.read_exact(4)?;
        let entity_id = i32::from_be_bytes([__buf[0],__buf[1],__buf[2],__buf[3]]);
        Ok(Self { window_id, nb_slots, entity_id })
    }
}

impl ClientboundPacket for OpenHorseWindow {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.nb_slots, writer)?;
        writer.write_all(&self.entity_id.to_be_bytes())?;
        Ok(())
    }
}
