//! Packet `open_window` (play/clientbound, id 0x30).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/open_window.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x30;

/// OpenWindow packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct OpenWindow {
    /// Auto-generated field.
    pub wid: i32,
    /// Auto-generated field.
    pub it: i32,
    /// Auto-generated field.
    pub title: String,
}

impl OpenWindow {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let wid = varint::read(reader)?;
        let it = varint::read(reader)?;
        let title = string::read(reader)?;
        Ok(Self { wid, it, title })
    }
}

impl ClientboundPacket for OpenWindow {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.wid, writer)?;
        varint::write(self.it, writer)?;
        string::write(&self.title, writer)?;
        Ok(())
    }
}
