//! Packet `open_horse_window` (play/clientbound, id 0x20).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/open_horse_window.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0x20;
