//! Packet `open_sign_entity` (play/clientbound, id 0x31).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/open_sign_entity.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::codec::position;
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x31;

/// OpenSignEntity packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct OpenSignEntity {
    /// Auto-generated field.
    pub location: (i32, i32, i32),
    /// Auto-generated field.
    pub is_front_text: bool,
}

impl OpenSignEntity {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let location = position::read(reader)?;
        let is_front_text = { let __b = reader.read_exact(1)?[0]; if __b > 1 { return Err(ProtocolError::DecodeError(format!("is_front_text: {}", __b))); } __b != 0 };
        Ok(Self { location, is_front_text })
    }
}

impl ClientboundPacket for OpenSignEntity {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        position::write(&self.location, writer)?;
        writer.write_all(&[if self.is_front_text { 1 } else { 0 }])?;
        Ok(())
    }
}
