//! Packet `open_book` (play/clientbound, id 0x2F).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/open_book.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x2F;

/// OpenBook packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct OpenBook {
    /// Auto-generated field.
    pub hand: i32,
}

impl OpenBook {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let hand = varint::read(reader)?;
        Ok(Self { hand })
    }
}

impl ClientboundPacket for OpenBook {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.hand, writer)?;
        Ok(())
    }
}
