//! Packet `ping` (play/clientbound, id 0x32).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/ping.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x32;

/// Ping packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct Ping {
    /// Auto-generated field.
    pub pid: i32,
}

impl Ping {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let __buf = reader.read_exact(4)?;
        let pid = i32::from_be_bytes([__buf[0],__buf[1],__buf[2],__buf[3]]);
        Ok(Self { pid })
    }
}

impl ClientboundPacket for Ping {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&self.pid.to_be_bytes())?;
        Ok(())
    }
}
