//! Packet `playerlist_header` (play/clientbound, id 0x65).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/playerlist_header.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x65;

/// PlayerlistHeader packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct PlayerlistHeader {
    /// Auto-generated field.
    pub header: String,
    /// Auto-generated field.
    pub footer: String,
}

impl PlayerlistHeader {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let header = string::read(reader)?;
        let footer = string::read(reader)?;
        Ok(Self { header, footer })
    }
}

impl ClientboundPacket for PlayerlistHeader {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        string::write(&self.header, writer)?;
        string::write(&self.footer, writer)?;
        Ok(())
    }
}
