//! Packet `player_chat` (play/clientbound, id 0x35).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/player_chat.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::codec::uuid_codec::{self as uuid_c, Uuid};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x35;

/// PlayerChat packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct PlayerChat {
    /// Auto-generated field.
    pub sender: Uuid,
    /// Auto-generated field.
    pub payload: Vec<u8>,
}

impl PlayerChat {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let sender = uuid_c::read(reader)?;
        let payload = reader.read_exact(reader.remaining())?.to_vec();
        Ok(Self { sender, payload })
    }
}

impl ClientboundPacket for PlayerChat {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        uuid_c::write(&self.sender, writer)?;
        writer.write_all(&self.payload)?;
        Ok(())
    }
}
