//! Packet `player_chat` (play/clientbound, id 0x35).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/player_chat.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0x35;
