//! Packet `player_remove` (play/clientbound, id 0x39).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/player_remove.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::codec::uuid_codec::{self as uuid_c, Uuid};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x39;

/// PlayerRemove packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct PlayerRemove {
    /// Auto-generated field.
    pub n: i32,
    /// Auto-generated field.
    pub players: Vec<Uuid>,
}

impl PlayerRemove {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let n = varint::read(reader)?;
        let players = { let mut __v: Vec<Uuid> = Vec::with_capacity(n as usize); for _ in 0..n { __v.push(uuid_c::read(reader)?); } __v };
        Ok(Self { n, players })
    }
}

impl ClientboundPacket for PlayerRemove {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.n, writer)?;
        Ok(())
    }
}
