//! Packet `player_info` (play/clientbound, id 0x3A).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/player_info.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0x3A;
