//! Packet `player_info` (play/clientbound, id 0x3A).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/player_info.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x3A;

/// PlayerInfo packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct PlayerInfo {
    /// Auto-generated field.
    pub actions_mask: i8,
    /// Auto-generated field.
    pub payload: Vec<u8>,
}

impl PlayerInfo {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let __buf = reader.read_exact(1)?;
        let actions_mask = __buf[0] as i8;
        let payload = reader.read_exact(reader.remaining())?.to_vec();
        Ok(Self {
            actions_mask,
            payload,
        })
    }
}

impl ClientboundPacket for PlayerInfo {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&[self.actions_mask as u8])?;
        writer.write_all(&self.payload)?;
        Ok(())
    }
}
