//! Packet `player_remove` (play/clientbound, id 0x39).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/player_remove.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0x39;
