//! Packet `profileless_chat` (play/clientbound, id 0x1B).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/profileless_chat.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x1B;

/// ProfilelessChat packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct ProfilelessChat {
    /// Auto-generated field.
    pub message: String,
    /// Auto-generated field.
    pub chat_type: i32,
    /// Auto-generated field.
    pub name: String,
    /// Auto-generated field.
    pub target: Option<String>,
}

impl ProfilelessChat {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let message = string::read(reader)?;
        let chat_type = varint::read(reader)?;
        let name = string::read(reader)?;
        let present = reader.read_exact(1)?[0];
        let target = match present {
            0 => None,
            1 => Some(string::read(reader)?),
            other => {
                return Err(ProtocolError::DecodeError(format!(
                    "target.present: {}",
                    other
                )))
            }
        };
        Ok(Self {
            message,
            chat_type,
            name,
            target,
        })
    }
}

impl ClientboundPacket for ProfilelessChat {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        string::write(&self.message, writer)?;
        varint::write(self.chat_type, writer)?;
        string::write(&self.name, writer)?;
        match &self.target {
            None => writer.write_all(&[0])?,
            Some(v) => {
                writer.write_all(&[1])?;
                string::write(v, writer)?;
            }
        }
        Ok(())
    }
}
