//! Packet `rel_entity_move` (play/clientbound, id 0x2B).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/rel_entity_move.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0x2B;
