//! Packet `rel_entity_move` (play/clientbound, id 0x2B).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/rel_entity_move.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x2B;

/// RelEntityMove packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct RelEntityMove {
    /// Auto-generated field.
    pub entity_id: i32,
    /// Auto-generated field.
    pub dx: i16,
    /// Auto-generated field.
    pub dy: i16,
    /// Auto-generated field.
    pub dz: i16,
    /// Auto-generated field.
    pub on_ground: bool,
}

impl RelEntityMove {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let entity_id = varint::read(reader)?;
        let __buf = reader.read_exact(6)?;
        let dx = i16::from_be_bytes([__buf[0],__buf[1]]);
        let dy = i16::from_be_bytes([__buf[2],__buf[3]]);
        let dz = i16::from_be_bytes([__buf[4],__buf[5]]);
        let on_ground = { let __b = reader.read_exact(1)?[0]; if __b > 1 { return Err(ProtocolError::DecodeError(format!("on_ground: {}", __b))); } __b != 0 };
        Ok(Self { entity_id, dx, dy, dz, on_ground })
    }
}

impl ClientboundPacket for RelEntityMove {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.entity_id, writer)?;
        writer.write_all(&self.dx.to_be_bytes())?;
        writer.write_all(&self.dy.to_be_bytes())?;
        writer.write_all(&self.dz.to_be_bytes())?;
        writer.write_all(&[if self.on_ground { 1 } else { 0 }])?;
        Ok(())
    }
}
