//! Packet `remove_entity_effect` (play/clientbound, id 0x3F).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/remove_entity_effect.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x3F;

/// RemoveEntityEffect packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct RemoveEntityEffect {
    /// Auto-generated field.
    pub entity_id: i32,
    /// Auto-generated field.
    pub effect_id: i32,
}

impl RemoveEntityEffect {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let entity_id = varint::read(reader)?;
        let effect_id = varint::read(reader)?;
        Ok(Self { entity_id, effect_id })
    }
}

impl ClientboundPacket for RemoveEntityEffect {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.entity_id, writer)?;
        varint::write(self.effect_id, writer)?;
        Ok(())
    }
}
