//! Packet `resource_pack_send` (play/clientbound, id 0x40).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/resource_pack_send.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0x40;
