//! Packet `resource_pack_send` (play/clientbound, id 0x40).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/resource_pack_send.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x40;

/// ResourcePackSend packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct ResourcePackSend {
    /// Auto-generated field.
    pub url: String,
    /// Auto-generated field.
    pub hash: String,
    /// Auto-generated field.
    pub forced: bool,
    /// Auto-generated field.
    pub prompt_message: Option<String>,
}

impl ResourcePackSend {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let url = string::read(reader)?;
        let hash = string::read(reader)?;
        let forced = { let __b = reader.read_exact(1)?[0]; if __b > 1 { return Err(ProtocolError::DecodeError(format!("forced: {}", __b))); } __b != 0 };
        let p = reader.read_exact(1)?[0];
        let prompt_message = match p {
            0 => None,
            1 => Some(string::read(reader)?),
            other => return Err(ProtocolError::DecodeError(format!("prompt_message.present: {}", other))),
        };
        Ok(Self { url, hash, forced, prompt_message })
    }
}

impl ClientboundPacket for ResourcePackSend {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        string::write(&self.url, writer)?;
        string::write(&self.hash, writer)?;
        writer.write_all(&[if self.forced { 1 } else { 0 }])?;
        match &self.prompt_message {
            None => writer.write_all(&[0])?,
            Some(v) => {
                writer.write_all(&[1])?;
                string::write(v, writer)?;
            }
        }
        Ok(())
    }
}
