//! Packet `scoreboard_objective` (play/clientbound, id 0x58).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/scoreboard_objective.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x58;

/// ScoreboardObjective packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct ScoreboardObjective {
    /// Auto-generated field.
    pub name: String,
    /// Auto-generated field.
    pub action: i8,
    /// Auto-generated field.
    pub display_text: Option<String>,
    /// Auto-generated field.
    pub objective_type: Option<i32>,
}

impl ScoreboardObjective {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let name = string::read(reader)?;
        let __buf = reader.read_exact(1)?;
        let action = __buf[0] as i8;
        let mut display_text: Option<String> = None;
        let mut objective_type: Option<i32> = None;
        if action == 0 || action == 2 {
            display_text = Some(string::read(reader)?);
            objective_type = Some(varint::read(reader)?);
        }
        Ok(Self {
            name,
            action,
            display_text,
            objective_type,
        })
    }
}

impl ClientboundPacket for ScoreboardObjective {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        string::write(&self.name, writer)?;
        writer.write_all(&[self.action as u8])?;
        Ok(())
    }
}
