//! Packet `scoreboard_score` (play/clientbound, id 0x5B).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/scoreboard_score.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0x5B;
