//! Packet `scoreboard_display_objective` (play/clientbound, id 0x51).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/scoreboard_display_objective.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x51;

/// ScoreboardDisplayObjective packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct ScoreboardDisplayObjective {
    /// Auto-generated field.
    pub position: i8,
    /// Auto-generated field.
    pub name: String,
}

impl ScoreboardDisplayObjective {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let __buf = reader.read_exact(1)?;
        let position = __buf[0] as i8;
        let name = string::read(reader)?;
        Ok(Self { position, name })
    }
}

impl ClientboundPacket for ScoreboardDisplayObjective {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&[self.position as u8])?;
        string::write(&self.name, writer)?;
        Ok(())
    }
}
