//! Packet `scoreboard_objective` (play/clientbound, id 0x58).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/scoreboard_objective.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0x58;
