//! Packet `select_advancement_tab` (play/clientbound, id 0x44).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/select_advancement_tab.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0x44;
