//! Packet `server_data` (play/clientbound, id 0x45).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/server_data.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0x45;
