//! Packet `server_data` (play/clientbound, id 0x45).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/server_data.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x45;

/// ServerData packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct ServerData {
    /// Auto-generated field.
    pub motd: String,
    /// Auto-generated field.
    pub present: u8,
    /// Auto-generated field.
    pub n: Option<i32>,
    /// Auto-generated field.
    pub enforces_secure_chat: bool,
}

impl ServerData {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let motd = string::read(reader)?;
        let present = reader.read_exact(1)?[0];
        let n = match present {
            0 => None,
            1 => Some(varint::read(reader)?),
            other => return Err(ProtocolError::DecodeError(format!("n.present: {}", other))),
        };
        let enforces_secure_chat = { let __b = reader.read_exact(1)?[0]; if __b > 1 { return Err(ProtocolError::DecodeError(format!("enforces_secure_chat: {}", __b))); } __b != 0 };
        Ok(Self { motd, present, n, enforces_secure_chat })
    }
}

impl ClientboundPacket for ServerData {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        string::write(&self.motd, writer)?;
        match &self.n {
            None => writer.write_all(&[0])?,
            Some(v) => {
                writer.write_all(&[1])?;
                varint::write(*v, writer)?;
            }
        }
        Ok(())
    }
}
