//! Packet `set_slot` (play/clientbound, id 0x14).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/set_slot.py.

use crate::codec::slot;
use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x14;

/// SetSlot packet body (auto-generated).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct SetSlot {
    /// Auto-generated field.
    pub window_id: i8,
    /// Auto-generated field.
    pub state_id: i32,
    /// Auto-generated field.
    pub slot_index: i16,
    /// Auto-generated field.
    pub item: Option<crate::codec::slot::SlotData>,
}

impl SetSlot {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let __buf = reader.read_exact(1)?;
        let window_id = __buf[0] as i8;
        let state_id = varint::read(reader)?;
        let __buf = reader.read_exact(2)?;
        let slot_index = i16::from_be_bytes([__buf[0], __buf[1]]);
        let item = slot::read(reader)?;
        Ok(Self {
            window_id,
            state_id,
            slot_index,
            item,
        })
    }
}

impl ClientboundPacket for SetSlot {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&[self.window_id as u8])?;
        varint::write(self.state_id, writer)?;
        writer.write_all(&self.slot_index.to_be_bytes())?;
        slot::write(self.item.as_ref(), writer)?;
        Ok(())
    }
}
