//! Packet `set_cooldown` (play/clientbound, id 0x15).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/set_cooldown.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x15;

/// SetCooldown packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct SetCooldown {
    /// Auto-generated field.
    pub item_id: i32,
    /// Auto-generated field.
    pub cooldown_ticks: i32,
}

impl SetCooldown {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let item_id = varint::read(reader)?;
        let cooldown_ticks = varint::read(reader)?;
        Ok(Self {
            item_id,
            cooldown_ticks,
        })
    }
}

impl ClientboundPacket for SetCooldown {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.item_id, writer)?;
        varint::write(self.cooldown_ticks, writer)?;
        Ok(())
    }
}
