//! Packet `set_passengers` (play/clientbound, id 0x59).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/set_passengers.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x59;

/// SetPassengers packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct SetPassengers {
    /// Auto-generated field.
    pub entity_id: i32,
    /// Auto-generated field.
    pub n: i32,
    /// Auto-generated field.
    pub passengers: Vec<i32>,
}

impl SetPassengers {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let entity_id = varint::read(reader)?;
        let n = varint::read(reader)?;
        let passengers = { let mut __v: Vec<i32> = Vec::with_capacity(n as usize); for _ in 0..n { __v.push(varint::read(reader)?); } __v };
        Ok(Self { entity_id, n, passengers })
    }
}

impl ClientboundPacket for SetPassengers {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.entity_id, writer)?;
        varint::write(self.n, writer)?;
        Ok(())
    }
}
