//! Packet `set_passengers` (play/clientbound, id 0x59).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/set_passengers.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0x59;
