//! Packet `set_title_time` (play/clientbound, id 0x60).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/set_title_time.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x60;

/// SetTitleTime packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct SetTitleTime {
    /// Auto-generated field.
    pub fi: i32,
    /// Auto-generated field.
    pub st: i32,
    /// Auto-generated field.
    pub fo: i32,
}

impl SetTitleTime {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let __buf = reader.read_exact(12)?;
        let fi = i32::from_be_bytes([__buf[0],__buf[1],__buf[2],__buf[3]]);
        let st = i32::from_be_bytes([__buf[4],__buf[5],__buf[6],__buf[7]]);
        let fo = i32::from_be_bytes([__buf[8],__buf[9],__buf[10],__buf[11]]);
        Ok(Self { fi, st, fo })
    }
}

impl ClientboundPacket for SetTitleTime {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&self.fi.to_be_bytes())?;
        writer.write_all(&self.st.to_be_bytes())?;
        writer.write_all(&self.fo.to_be_bytes())?;
        Ok(())
    }
}
