//! Packet `set_slot` (play/clientbound, id 0x14).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/set_slot.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::codec::slot;
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x14;

/// SetSlot packet body (auto-generated).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct SetSlot {
    /// Auto-generated field.
    pub wid: i8,
    /// Auto-generated field.
    pub state: i32,
    /// Auto-generated field.
    pub si: i16,
    /// Auto-generated field.
    pub item: Option<crate::codec::slot::SlotData>,
}

impl SetSlot {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let __buf = reader.read_exact(1)?;
        let wid = __buf[0] as i8;
        let state = varint::read(reader)?;
        let __buf = reader.read_exact(2)?;
        let si = i16::from_be_bytes([__buf[0],__buf[1]]);
        let item = slot::read(reader)?;
        Ok(Self { wid, state, si, item })
    }
}

impl ClientboundPacket for SetSlot {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&[self.wid as u8])?;
        varint::write(self.state, writer)?;
        writer.write_all(&self.si.to_be_bytes())?;
        slot::write(self.item.as_ref(), writer)?;
        Ok(())
    }
}
