//! Packet `spawn_entity` (play/clientbound, id 0x01).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/spawn_entity.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::codec::uuid_codec::{self as uuid_c, Uuid};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x01;

/// SpawnEntity packet body (auto-generated).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct SpawnEntity {
    /// Auto-generated field.
    pub entity_id: i32,
    /// Auto-generated field.
    pub object_uuid: Uuid,
    /// Auto-generated field.
    pub entity_type: i32,
    /// Auto-generated field.
    pub x: f64,
    /// Auto-generated field.
    pub y: f64,
    /// Auto-generated field.
    pub z: f64,
    /// Auto-generated field.
    pub pitch: i8,
    /// Auto-generated field.
    pub yaw: i8,
    /// Auto-generated field.
    pub head_pitch: i8,
    /// Auto-generated field.
    pub object_data: i32,
    /// Auto-generated field.
    pub vx: i16,
    /// Auto-generated field.
    pub vy: i16,
    /// Auto-generated field.
    pub vz: i16,
}

impl SpawnEntity {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let entity_id = varint::read(reader)?;
        let object_uuid = uuid_c::read(reader)?;
        let entity_type = varint::read(reader)?;
        let __buf = reader.read_exact(24)?;
        let x = f64::from_be_bytes([__buf[0],__buf[1],__buf[2],__buf[3],__buf[4],__buf[5],__buf[6],__buf[7]]);
        let y = f64::from_be_bytes([__buf[8],__buf[9],__buf[10],__buf[11],__buf[12],__buf[13],__buf[14],__buf[15]]);
        let z = f64::from_be_bytes([__buf[16],__buf[17],__buf[18],__buf[19],__buf[20],__buf[21],__buf[22],__buf[23]]);
        let __buf = reader.read_exact(3)?;
        let pitch = __buf[0] as i8;
        let yaw = __buf[1] as i8;
        let head_pitch = __buf[2] as i8;
        let object_data = varint::read(reader)?;
        let __buf = reader.read_exact(6)?;
        let vx = i16::from_be_bytes([__buf[0],__buf[1]]);
        let vy = i16::from_be_bytes([__buf[2],__buf[3]]);
        let vz = i16::from_be_bytes([__buf[4],__buf[5]]);
        Ok(Self { entity_id, object_uuid, entity_type, x, y, z, pitch, yaw, head_pitch, object_data, vx, vy, vz })
    }
}

impl ClientboundPacket for SpawnEntity {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.entity_id, writer)?;
        uuid_c::write(&self.object_uuid, writer)?;
        varint::write(self.entity_type, writer)?;
        writer.write_all(&self.x.to_be_bytes())?;
        writer.write_all(&self.y.to_be_bytes())?;
        writer.write_all(&self.z.to_be_bytes())?;
        writer.write_all(&[self.pitch as u8])?;
        writer.write_all(&[self.yaw as u8])?;
        writer.write_all(&[self.head_pitch as u8])?;
        varint::write(self.object_data, writer)?;
        writer.write_all(&self.vx.to_be_bytes())?;
        writer.write_all(&self.vy.to_be_bytes())?;
        writer.write_all(&self.vz.to_be_bytes())?;
        Ok(())
    }
}
