//! Packet `spawn_position` (play/clientbound, id 0x50).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/spawn_position.py.

use crate::codec::position;
use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x50;

/// SpawnPosition packet body (auto-generated).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct SpawnPosition {
    /// Auto-generated field.
    pub location: (i32, i32, i32),
    /// Auto-generated field.
    pub angle: f32,
}

impl SpawnPosition {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let location = position::read(reader)?;
        let __buf = reader.read_exact(4)?;
        let angle = f32::from_be_bytes([__buf[0], __buf[1], __buf[2], __buf[3]]);
        Ok(Self { location, angle })
    }
}

impl ClientboundPacket for SpawnPosition {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        position::write(&self.location, writer)?;
        writer.write_all(&self.angle.to_be_bytes())?;
        Ok(())
    }
}
