//! Packet `stop_sound` (play/clientbound, id 0x63).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/stop_sound.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0x63;
