//! Packet `system_chat` (play/clientbound, id 0x64).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/system_chat.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x64;

/// SystemChat packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct SystemChat {
    /// Auto-generated field.
    pub content: String,
    /// Auto-generated field.
    pub is_action_bar: bool,
}

impl SystemChat {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let content = string::read(reader)?;
        let is_action_bar = { let __b = reader.read_exact(1)?[0]; if __b > 1 { return Err(ProtocolError::DecodeError(format!("is_action_bar: {}", __b))); } __b != 0 };
        Ok(Self { content, is_action_bar })
    }
}

impl ClientboundPacket for SystemChat {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        string::write(&self.content, writer)?;
        Ok(())
    }
}
