//! Packet `tile_entity_data` (play/clientbound, id 0x08).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/tile_entity_data.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::codec::nbt;
use crate::codec::position;
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x08;

/// TileEntityData packet body (auto-generated).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct TileEntityData {
    /// Auto-generated field.
    pub loc: (i32, i32, i32),
    /// Auto-generated field.
    pub act: i32,
    /// Auto-generated field.
    pub tag: Option<crate::codec::nbt::NbtTag>,
}

impl TileEntityData {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let loc = position::read(reader)?;
        let act = varint::read(reader)?;
        let tag = nbt::read(reader)?;
        Ok(Self { loc, act, tag })
    }
}

impl ClientboundPacket for TileEntityData {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        position::write(&self.loc, writer)?;
        varint::write(self.act, writer)?;
        nbt::write(self.tag.as_ref(), writer)?;
        Ok(())
    }
}
