//! Packet `trade_list` (play/clientbound, id 0x2A).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/trade_list.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x2A;

/// TradeList packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct TradeList {
    /// Auto-generated field.
    pub window_id: i32,
    /// Auto-generated field.
    pub payload: Vec<u8>,
}

impl TradeList {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let window_id = varint::read(reader)?;
        let payload = reader.read_exact(reader.remaining())?.to_vec();
        Ok(Self { window_id, payload })
    }
}

impl ClientboundPacket for TradeList {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.window_id, writer)?;
        writer.write_all(&self.payload)?;
        Ok(())
    }
}
