//! Packet `unload_chunk` (play/clientbound, id 0x1E).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/unload_chunk.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x1E;

/// UnloadChunk packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct UnloadChunk {
    /// Auto-generated field.
    pub cx: i32,
    /// Auto-generated field.
    pub cz: i32,
}

impl UnloadChunk {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let __buf = reader.read_exact(8)?;
        let cx = i32::from_be_bytes([__buf[0],__buf[1],__buf[2],__buf[3]]);
        let cz = i32::from_be_bytes([__buf[4],__buf[5],__buf[6],__buf[7]]);
        Ok(Self { cx, cz })
    }
}

impl ClientboundPacket for UnloadChunk {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&self.cx.to_be_bytes())?;
        writer.write_all(&self.cz.to_be_bytes())?;
        Ok(())
    }
}
