//! Packet `unlock_recipes` (play/clientbound, id 0x3D).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/unlock_recipes.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0x3D;
