//! Packet `update_time` (play/clientbound, id 0x5E).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/update_time.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x5E;

/// UpdateTime packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct UpdateTime {
    /// Auto-generated field.
    pub age: i64,
    /// Auto-generated field.
    pub time: i64,
}

impl UpdateTime {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let __buf = reader.read_exact(16)?;
        let age = i64::from_be_bytes([
            __buf[0], __buf[1], __buf[2], __buf[3], __buf[4], __buf[5], __buf[6], __buf[7],
        ]);
        let time = i64::from_be_bytes([
            __buf[8], __buf[9], __buf[10], __buf[11], __buf[12], __buf[13], __buf[14], __buf[15],
        ]);
        Ok(Self { age, time })
    }
}

impl ClientboundPacket for UpdateTime {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&self.age.to_be_bytes())?;
        writer.write_all(&self.time.to_be_bytes())?;
        Ok(())
    }
}
