//! Packet `update_light` (play/clientbound, id 0x27).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/update_light.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x27;

/// UpdateLight packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct UpdateLight {
    /// Auto-generated field.
    pub chunk_x: i32,
    /// Auto-generated field.
    pub chunk_z: i32,
    /// Auto-generated field.
    pub payload: Vec<u8>,
}

impl UpdateLight {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let chunk_x = varint::read(reader)?;
        let chunk_z = varint::read(reader)?;
        let payload = reader.read_exact(reader.remaining())?.to_vec();
        Ok(Self {
            chunk_x,
            chunk_z,
            payload,
        })
    }
}

impl ClientboundPacket for UpdateLight {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.chunk_x, writer)?;
        varint::write(self.chunk_z, writer)?;
        writer.write_all(&self.payload)?;
        Ok(())
    }
}
