//! Packet `update_view_distance` (play/clientbound, id 0x4F).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/update_view_distance.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x4F;

/// UpdateViewDistance packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct UpdateViewDistance {
    /// Auto-generated field.
    pub view_distance: i32,
}

impl UpdateViewDistance {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let view_distance = varint::read(reader)?;
        Ok(Self { view_distance })
    }
}

impl ClientboundPacket for UpdateViewDistance {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.view_distance, writer)?;
        Ok(())
    }
}
