//! Packet `update_health` (play/clientbound, id 0x57).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/update_health.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x57;

/// UpdateHealth packet body (auto-generated).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct UpdateHealth {
    /// Auto-generated field.
    pub h: f32,
    /// Auto-generated field.
    pub f: i32,
    /// Auto-generated field.
    pub s: f32,
}

impl UpdateHealth {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let __buf = reader.read_exact(4)?;
        let h = f32::from_be_bytes([__buf[0],__buf[1],__buf[2],__buf[3]]);
        let f = varint::read(reader)?;
        let __buf = reader.read_exact(4)?;
        let s = f32::from_be_bytes([__buf[0],__buf[1],__buf[2],__buf[3]]);
        Ok(Self { h, f, s })
    }
}

impl ClientboundPacket for UpdateHealth {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&self.h.to_be_bytes())?;
        varint::write(self.f, writer)?;
        writer.write_all(&self.s.to_be_bytes())?;
        Ok(())
    }
}
