//! Packet `update_light` (play/clientbound, id 0x27).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/update_light.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0x27;
