//! Packet `update_view_position` (play/clientbound, id 0x4E).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/update_view_position.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x4E;

/// UpdateViewPosition packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct UpdateViewPosition {
    /// Auto-generated field.
    pub chunk_x: i32,
    /// Auto-generated field.
    pub chunk_z: i32,
}

impl UpdateViewPosition {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let chunk_x = varint::read(reader)?;
        let chunk_z = varint::read(reader)?;
        Ok(Self { chunk_x, chunk_z })
    }
}

impl ClientboundPacket for UpdateViewPosition {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.chunk_x, writer)?;
        varint::write(self.chunk_z, writer)?;
        Ok(())
    }
}
