//! Packet `vehicle_move` (play/clientbound, id 0x2E).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/vehicle_move.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x2E;

/// VehicleMove packet body (auto-generated).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VehicleMove {
    /// Auto-generated field.
    pub x: f64,
    /// Auto-generated field.
    pub y: f64,
    /// Auto-generated field.
    pub z: f64,
    /// Auto-generated field.
    pub yaw: f32,
    /// Auto-generated field.
    pub pitch: f32,
}

impl VehicleMove {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let __buf = reader.read_exact(24)?;
        let x = f64::from_be_bytes([
            __buf[0], __buf[1], __buf[2], __buf[3], __buf[4], __buf[5], __buf[6], __buf[7],
        ]);
        let y = f64::from_be_bytes([
            __buf[8], __buf[9], __buf[10], __buf[11], __buf[12], __buf[13], __buf[14], __buf[15],
        ]);
        let z = f64::from_be_bytes([
            __buf[16], __buf[17], __buf[18], __buf[19], __buf[20], __buf[21], __buf[22], __buf[23],
        ]);
        let __buf = reader.read_exact(8)?;
        let yaw = f32::from_be_bytes([__buf[0], __buf[1], __buf[2], __buf[3]]);
        let pitch = f32::from_be_bytes([__buf[4], __buf[5], __buf[6], __buf[7]]);
        Ok(Self {
            x,
            y,
            z,
            yaw,
            pitch,
        })
    }
}

impl ClientboundPacket for VehicleMove {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&self.x.to_be_bytes())?;
        writer.write_all(&self.y.to_be_bytes())?;
        writer.write_all(&self.z.to_be_bytes())?;
        writer.write_all(&self.yaw.to_be_bytes())?;
        writer.write_all(&self.pitch.to_be_bytes())?;
        Ok(())
    }
}
