//! Packet `window_items` (play/clientbound, id 0x12).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/window_items.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::codec::slot;
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x12;

/// WindowItems packet body (auto-generated).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct WindowItems {
    /// Auto-generated field.
    pub window_id: u8,
    /// Auto-generated field.
    pub state_id: i32,
    /// Auto-generated field.
    pub n: i32,
    /// Auto-generated field.
    pub items: Vec<Option<crate::codec::slot::SlotData>>,
    /// Auto-generated field.
    pub carried_item: Option<crate::codec::slot::SlotData>,
}

impl WindowItems {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let window_id = reader.read_exact(1)?[0];
        let state_id = varint::read(reader)?;
        let n = varint::read(reader)?;
        let items = { let mut __v: Vec<Option<crate::codec::slot::SlotData>> = Vec::with_capacity(n as usize); for _ in 0..n { __v.push(slot::read(reader)?); } __v };
        let carried_item = slot::read(reader)?;
        Ok(Self { window_id, state_id, n, items, carried_item })
    }
}

impl ClientboundPacket for WindowItems {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&[self.window_id])?;
        varint::write(self.state_id, writer)?;
        varint::write(self.n, writer)?;
        slot::write(self.carried_item.as_ref(), writer)?;
        Ok(())
    }
}
