//! Packet `window_items` (play/clientbound, id 0x12).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/window_items.py — STUB (decode pattern not yet supported).

pub const PACKET_ID: i32 = 0x12;
