//! Packet `world_particles` (play/clientbound, id 0x26).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/world_particles.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x26;

/// WorldParticles packet body (auto-generated).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct WorldParticles {
    /// Auto-generated field.
    pub particle_id: i32,
    /// Auto-generated field.
    pub long_distance: bool,
    /// Auto-generated field.
    pub x: f64,
    /// Auto-generated field.
    pub y: f64,
    /// Auto-generated field.
    pub z: f64,
    /// Auto-generated field.
    pub offset_x: f32,
    /// Auto-generated field.
    pub offset_y: f32,
    /// Auto-generated field.
    pub offset_z: f32,
    /// Auto-generated field.
    pub particle_data: f32,
    /// Auto-generated field.
    pub particle_count: i32,
    /// Auto-generated field.
    pub data: Vec<u8>,
}

impl WorldParticles {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let particle_id = varint::read(reader)?;
        let long_distance = {
            let __b = reader.read_exact(1)?[0];
            if __b > 1 {
                return Err(ProtocolError::DecodeError(format!(
                    "long_distance: {}",
                    __b
                )));
            }
            __b != 0
        };
        let __buf = reader.read_exact(24)?;
        let x = f64::from_be_bytes([
            __buf[0], __buf[1], __buf[2], __buf[3], __buf[4], __buf[5], __buf[6], __buf[7],
        ]);
        let y = f64::from_be_bytes([
            __buf[8], __buf[9], __buf[10], __buf[11], __buf[12], __buf[13], __buf[14], __buf[15],
        ]);
        let z = f64::from_be_bytes([
            __buf[16], __buf[17], __buf[18], __buf[19], __buf[20], __buf[21], __buf[22], __buf[23],
        ]);
        let __buf = reader.read_exact(16)?;
        let offset_x = f32::from_be_bytes([__buf[0], __buf[1], __buf[2], __buf[3]]);
        let offset_y = f32::from_be_bytes([__buf[4], __buf[5], __buf[6], __buf[7]]);
        let offset_z = f32::from_be_bytes([__buf[8], __buf[9], __buf[10], __buf[11]]);
        let particle_data = f32::from_be_bytes([__buf[12], __buf[13], __buf[14], __buf[15]]);
        let __buf = reader.read_exact(4)?;
        let particle_count = i32::from_be_bytes([__buf[0], __buf[1], __buf[2], __buf[3]]);
        let data = reader.read_exact(reader.remaining())?.to_vec();
        Ok(Self {
            particle_id,
            long_distance,
            x,
            y,
            z,
            offset_x,
            offset_y,
            offset_z,
            particle_data,
            particle_count,
            data,
        })
    }
}

impl ClientboundPacket for WorldParticles {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.particle_id, writer)?;
        writer.write_all(&[if self.long_distance { 1 } else { 0 }])?;
        writer.write_all(&self.x.to_be_bytes())?;
        writer.write_all(&self.y.to_be_bytes())?;
        writer.write_all(&self.z.to_be_bytes())?;
        writer.write_all(&self.offset_x.to_be_bytes())?;
        writer.write_all(&self.offset_y.to_be_bytes())?;
        writer.write_all(&self.offset_z.to_be_bytes())?;
        writer.write_all(&self.particle_data.to_be_bytes())?;
        writer.write_all(&self.particle_count.to_be_bytes())?;
        writer.write_all(&self.data)?;
        Ok(())
    }
}
