//! Packet `world_border_lerp_size` (play/clientbound, id 0x48).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/world_border_lerp_size.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x48;

/// WorldBorderLerpSize packet body (auto-generated).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct WorldBorderLerpSize {
    /// Auto-generated field.
    pub old: f64,
    /// Auto-generated field.
    pub new: f64,
    /// Auto-generated field.
    pub speed: i32,
}

impl WorldBorderLerpSize {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let __buf = reader.read_exact(16)?;
        let old = f64::from_be_bytes([__buf[0],__buf[1],__buf[2],__buf[3],__buf[4],__buf[5],__buf[6],__buf[7]]);
        let new = f64::from_be_bytes([__buf[8],__buf[9],__buf[10],__buf[11],__buf[12],__buf[13],__buf[14],__buf[15]]);
        let speed = varint::read(reader)?;
        Ok(Self { old, new, speed })
    }
}

impl ClientboundPacket for WorldBorderLerpSize {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&self.old.to_be_bytes())?;
        writer.write_all(&self.new.to_be_bytes())?;
        varint::write(self.speed, writer)?;
        Ok(())
    }
}
