//! Packet `world_border_warning_reach` (play/clientbound, id 0x4B).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/world_border_warning_reach.py.

use crate::codec::{
    string_codec as string, varint, varlong, BytesReader, BytesWriter, Reader, Writer,
};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x4B;

/// WorldBorderWarningReach packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct WorldBorderWarningReach {
    /// Auto-generated field.
    pub warning_blocks: i32,
}

impl WorldBorderWarningReach {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let warning_blocks = varint::read(reader)?;
        Ok(Self { warning_blocks })
    }
}

impl ClientboundPacket for WorldBorderWarningReach {
    fn state(&self) -> ConnectionState {
        ConnectionState::Play
    }
    fn packet_id(&self) -> i32 {
        PACKET_ID
    }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        varint::write(self.warning_blocks, writer)?;
        Ok(())
    }
}
