//! Packet `world_event` (play/clientbound, id 0x25).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/play/clientbound/world_event.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::codec::position;
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ClientboundPacket;

/// Numeric packet id within `(Play, Clientbound)`.
pub const PACKET_ID: i32 = 0x25;

/// WorldEvent packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct WorldEvent {
    /// Auto-generated field.
    pub effect_id: i32,
    /// Auto-generated field.
    pub location: (i32, i32, i32),
    /// Auto-generated field.
    pub data: i32,
    /// Auto-generated field.
    pub global_event: bool,
}

impl WorldEvent {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let __buf = reader.read_exact(4)?;
        let effect_id = i32::from_be_bytes([__buf[0],__buf[1],__buf[2],__buf[3]]);
        let location = position::read(reader)?;
        let __buf = reader.read_exact(4)?;
        let data = i32::from_be_bytes([__buf[0],__buf[1],__buf[2],__buf[3]]);
        let global_event = { let __b = reader.read_exact(1)?[0]; if __b > 1 { return Err(ProtocolError::DecodeError(format!("global_event: {}", __b))); } __b != 0 };
        Ok(Self { effect_id, location, data, global_event })
    }
}

impl ClientboundPacket for WorldEvent {
    fn state(&self) -> ConnectionState { ConnectionState::Play }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&self.effect_id.to_be_bytes())?;
        position::write(&self.location, writer)?;
        writer.write_all(&self.data.to_be_bytes())?;
        writer.write_all(&[if self.global_event { 1 } else { 0 }])?;
        Ok(())
    }
}
