#!/usr/bin/env python3
"""Generate per-entity-type Python subclass files from
``protocol-data/v763/entity_metadata.json``.

Each output file at ``python/minecraft_bot/entities/types/{snake_name}.py``
declares an Entity subclass with one ``@property`` per metadata index.
Property bodies read from ``self.metadata[index]`` with the typed
default appropriate to the metadata index's known semantics (most are
``Any`` until the runtime stream-decode tags them).

Idempotency
-----------

The auto-generated block is bounded by sentinel comments::

    # >>> auto-generated metadata accessors — DO NOT EDIT BELOW
    ...
    # <<< auto-generated metadata accessors

Anything *outside* this block (custom docstrings, helper methods,
parent-class imports) is preserved across re-runs. Anything *inside*
is overwritten.

Usage
-----

    python tools/generate_entity_subclasses.py            # all entity types
    python tools/generate_entity_subclasses.py --type sheep wolf
    python tools/generate_entity_subclasses.py --dry-run
    python tools/generate_entity_subclasses.py --force    # overwrite hand-edits OUTSIDE the auto block too
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
META_PATH = REPO_ROOT / "protocol-data" / "v763" / "entity_metadata.json"
TYPES_DIR = REPO_ROOT / "python" / "minecraft_bot" / "entities" / "types"

AUTO_BEGIN = "    # >>> auto-generated metadata accessors — DO NOT EDIT BELOW"
AUTO_END = "    # <<< auto-generated metadata accessors"


def snake(name: str) -> str:
    return re.sub(r"[^a-z0-9_]", "_", name.lower())


def camel(name: str) -> str:
    return "".join(p.capitalize() for p in snake(name).split("_"))


def render_accessors(metadata_keys: list[dict]) -> list[str]:
    """Return the body lines (already indented 4 spaces) for the auto block."""
    lines: list[str] = []
    if not metadata_keys:
        lines.append("    # (no entity-specific metadata indices)")
        return lines
    for entry in metadata_keys:
        idx = entry["index"]
        key_name = snake(entry["name"])
        # Reserved word avoidance
        if key_name in {"class", "type", "global"}:
            key_name = key_name + "_"
        lines.append("    @property")
        lines.append(f"    def {key_name}(self):")
        lines.append(f'        """Metadata index {idx}: ``{entry["name"]}``.\n')
        lines.append(f"        Returns the raw decoded value from the entity's data-watcher")
        lines.append(f"        stream, or ``None`` if the index has not been populated by")
        lines.append(f"        the server (entity hasn't sent a metadata update for it yet).")
        lines.append(f'        """')
        lines.append(f"        return self.metadata.get({idx})")
        lines.append("")
    return lines


def render_full_file(entry: dict) -> str:
    """Render the full file from scratch (used when file doesn't exist)."""
    class_name = camel(entry["name"])
    parent = entry["parent_class"]
    type_id = entry.get("type_id")  # may be None; set by caller
    auto_body = "\n".join(render_accessors(entry["metadata_keys"]))

    return f'''"""Entity subclass for `{entry["name"]}` (type id {type_id}).

Auto-generated by ``tools/generate_entity_subclasses.py``.

Hand-edits BELOW the auto-generated block are preserved across
re-generation. Hand-edits inside the auto block are wiped.
"""

from __future__ import annotations

from minecraft_bot.entities.base import {parent}


class {class_name}({parent}):
    """`{entry["display_name"]}` entity ({entry["category"]} category)."""

    ENTITY_TYPE_ID = {type_id}
    ENTITY_NAME = "{entry["name"]}"

{AUTO_BEGIN}
{auto_body}
{AUTO_END}
'''


def update_existing(path: Path, entry: dict) -> str:
    """Re-render only the auto block; keep everything else intact."""
    src = path.read_text(encoding="utf-8")
    auto_body = "\n".join(render_accessors(entry["metadata_keys"]))
    new_block = f"{AUTO_BEGIN}\n{auto_body}\n{AUTO_END}"
    # Replace between AUTO_BEGIN and AUTO_END (inclusive of both lines)
    pattern = re.compile(
        re.escape(AUTO_BEGIN) + r".*?" + re.escape(AUTO_END),
        re.DOTALL,
    )
    if not pattern.search(src):
        # File exists but lacks markers — leave alone (hand-written file)
        return src
    return pattern.sub(new_block, src)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--type", nargs="*", help="restrict to these entity names")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--force", action="store_true",
                        help="overwrite whole file (incl. hand-edits) instead of just the auto block")
    args = parser.parse_args(argv)

    meta = json.loads(META_PATH.read_text(encoding="utf-8"))
    TYPES_DIR.mkdir(parents=True, exist_ok=True)
    init_path = TYPES_DIR / "__init__.py"

    n_written = 0
    n_skipped = 0
    class_map: list[tuple[int, str, str]] = []  # (type_id, name, ClassName)

    for type_id_str, entry in meta.items():
        type_id = int(type_id_str)
        entry["type_id"] = type_id
        name = entry["name"]
        if args.type and name not in args.type:
            continue
        target = TYPES_DIR / f"{snake(name)}.py"
        class_map.append((type_id, name, camel(name)))

        if target.exists() and not args.force:
            new_src = update_existing(target, entry)
            if new_src == target.read_text(encoding="utf-8"):
                n_skipped += 1
                continue
            if args.dry_run:
                print(f"[dry-run] would update auto block in {target.relative_to(REPO_ROOT)}")
            else:
                target.write_text(new_src, encoding="utf-8")
                n_written += 1
        else:
            if args.dry_run:
                print(f"[dry-run] would write {target.relative_to(REPO_ROOT)}")
            else:
                target.write_text(render_full_file(entry), encoding="utf-8")
                n_written += 1

    # Regenerate __init__.py with the type-id -> class lookup.
    init_lines = ['"""Per-entity-type subclass imports + lookup map."""',
                  "",
                  "from __future__ import annotations",
                  ""]
    for _, name, cls in sorted(class_map, key=lambda x: x[0]):
        init_lines.append(f"from minecraft_bot.entities.types.{snake(name)} import {cls}")
    init_lines.append("")
    init_lines.append("# type_id -> subclass (filled in here for fast lookup at runtime)")
    init_lines.append("LOOKUP: dict[int, type] = {")
    for type_id, name, cls in sorted(class_map, key=lambda x: x[0]):
        init_lines.append(f"    {type_id}: {cls},  # {name}")
    init_lines.append("}")
    init_lines.append("")
    init_lines.append("def lookup_class(type_id: int) -> type:")
    init_lines.append('    """Resolve a clientbound entity-type-id to its Python subclass."""')
    init_lines.append("    from minecraft_bot.entities.base import Entity")
    init_lines.append("    return LOOKUP.get(type_id, Entity)")
    init_lines.append("")

    if not args.dry_run:
        init_path.write_text("\n".join(init_lines), encoding="utf-8")

    summary = (
        f"entity-subclass codegen: wrote/updated {n_written}, "
        f"unchanged {n_skipped}, total {len(class_map)}"
    )
    if args.dry_run:
        summary = "[dry-run] " + summary
    print(summary, file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
