//! Packet `ping` (status/serverbound, id 0x01).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/status/serverbound/ping.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Status, Serverbound)`.
pub const PACKET_ID: i32 = 0x01;

/// Ping packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct Ping {
    /// Auto-generated field.
    pub time: i64,
}

impl Ping {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        let time = i64::from_be_bytes({ let _b = reader.read_exact(8)?; [_b[0],_b[1],_b[2],_b[3],_b[4],_b[5],_b[6],_b[7]] });
        Ok(Self { time })
    }
}

impl ServerboundPacket for Ping {
    fn state(&self) -> ConnectionState { ConnectionState::Status }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        writer.write_all(&self.time.to_be_bytes())?;
        Ok(())
    }
}
