//! Packet `ping_start` (status/serverbound, id 0x00).
//!
//! Auto-generated by tools/generate_rust_packets.py from
//! python/minecraft_bot/protocol/v763/packets/status/serverbound/ping_start.py.

use crate::codec::{varint, varlong, string_codec as string, BytesReader, BytesWriter, Reader, Writer};
use crate::errors::ProtocolError;
use crate::protocol::v763::states::ConnectionState;
use crate::protocol::v763::ServerboundPacket;

/// Numeric packet id within `(Status, Serverbound)`.
pub const PACKET_ID: i32 = 0x00;

/// PingStart packet body (auto-generated).
#[derive(Debug, Clone, Eq, PartialEq, Default)]
pub struct PingStart {

}

impl PingStart {
    /// Decode from `reader`.
    pub fn decode(reader: &mut BytesReader<'_>) -> Result<Self, ProtocolError> {
        
        Ok(Self {  })
    }
}

impl ServerboundPacket for PingStart {
    fn state(&self) -> ConnectionState { ConnectionState::Status }
    fn packet_id(&self) -> i32 { PACKET_ID }
    fn encode(&self, writer: &mut BytesWriter) -> Result<(), ProtocolError> {
        Ok::<(), ProtocolError>(())?;
        Ok(())
    }
}
